### PR TITLE
fix: Coverity Scan analysis warnings

### PR DESCRIPTION
**Pull request by disaykin**
Analysis Summary:
       New defects found: 0
       Defects eliminated: 15

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by disaykin** [comment]
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
@disaykin it's running now, had to reset Jenkins the other day cause an update broke it ¯\_(ツ)_/¯

**Pull request merged**
