### PR TITLE
libusermode: add command line switch for pf/injection mode

### PR DESCRIPTION
**Pull request by disaykin**

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by disaykin** [comment]
@tklengyel I don't know why CI starts failing on
```
../src/libusermode/userhook.cpp:169:5: error: missing field '_pad' initializer [-Werror,-Wmissing-field-initializers]
  169 |     ACCESS_CONTEXT(ctx,
      |     ^
/opt/libvmi/include/libvmi/libvmi.h:765:5: note: expanded from macro 'ACCESS_CONTEXT'
  765 |     }
      |     ^
../src/libusermode/userhook.cpp:253:5: error: missing field 'targets' initializer [-Werror,-Wmissing-field-initializers]
  253 |     };
      |     ^
../src/libusermode/userhook.cpp:267:5: error: missing field '_pad' initializer [-Werror,-Wmissing-field-initializers]
  267 |     ACCESS_CONTEXT(ctx,
      |     ^
/opt/libvmi/include/libvmi/libvmi.h:765:5: note: expanded from macro 'ACCESS_CONTEXT'
  765 |     }
      |     ^
3 errors generated.
```

**Comment by disaykin** [comment]
@tklengyel I see you already fixed this in #1719

**Pull request merged**
