### PR TITLE
[memdump] Provide default DLL hook list for memdump plugin if not provided by user

### PR DESCRIPTION
**Pull request by icedevml**

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
```
1572136813.058941 DRAKVUF v0.7-b75bc66
Plugin memdump startup failed!
```

If no profile is provided for memdump to start with should just bail but not block the whole startup of DRAKVUF

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by icedevml** [comment]
Seems I didn't staged all the necessary changes. Gonna check it soon.

**Comment by icedevml** [comment]
@tklengyel for some reason this works for me:
```
src/drakvuf -v -d windows7-sp1 -r ../windows7-sp1.rekall.json
```

what Windows version is failing and what is the faulting command line?

**Comment by tklengyel** [comment]
I got the error with 32-bit Windows 7.

**Comment by icedevml** [comment]
Seems like SysWOW64 was not available ( :D ) or some related problem. I will check.

**Comment by icedevml** [comment]
Seems like `KiSystemServiceHandler` is not present in Windows 7 x86. I would have to dig deeper to find proper replacement or just disable the feature for x86 guests.

**Comment by icedevml** [comment]
Ok, unfortunately it is not so easy to support 32 bit x86 and for now we have identified at least two different problems that prevent it.

I've added a guard to disable usermode hooking completely if the page mode is not `VMI_PM_IA32E`. I'm pretty short on time till the end of the year, but we will get back to it someday.

**Comment by tklengyel** [comment]
Valgrind caught a leak at:
/shared/jenkins/DRAKVUF-build/src/plugins/memdump/userhook.cpp:292
```
 292     drakvuf_trap_t* trap = (drakvuf_trap_t*)g_try_malloc0(sizeof(drakvuf_trap_t));

**Comment by icedevml** [comment]
@tklengyel AFAIK traps are automatically freed by DRAKVUF when it is stopped? Or not?

**Comment by tklengyel** [comment]
@icedevml No, traps are stopped but memory management is up to each plugin. There is no garbage collection.

**Comment by icedevml** [comment]
Okay, I will address this.

**Comment by tklengyel** [comment]
Valgrind now says 
```
/shared/jenkins/DRAKVUF-build/src/plugins/memdump/userhook.cpp:1066
Mismatched free() / delete / delete []

**Comment by icedevml** [comment]
Seems like it's finally sorted out.

**Pull request merged**
