### PR TITLE
Add INJECTION_ERROR exit code

### PR DESCRIPTION
**Pull request by chivay**
Add a new return code to indicate an injector error.

### CODE REVIEW

**Comment by icedevml** [comment]
@drakvuf-jenkins Retest this please.

**Comment by icedevml** [comment]
@drakvuf-jenkins This is OK to test.

**Comment by icedevml** [comment]
(I was wondering whether this works for merged PRs :trollface: )

**Comment by tklengyel** [comment]
Doesn't look like ;)

**Pull request merged**
