### PR TITLE
fileextractor fix logic

### PR DESCRIPTION
**Pull request by EscardosS**
Small fix for algorithm logic:
First `NtWriteFile` was not handled properly for files opened with `FILE_APPEND_DATA` flag

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by EscardosS** [comment]
I got an error even though the plugin was not running:

https://ci.drakvuf.com/job/DRAKVUF-windows7-sp1-x64/1149/console

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by EscardosS** [comment]
Looks like VM not started 

https://ci.drakvuf.com/job/DRAKVUF-windows10/918/console

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Pull request merged**
