### PR TITLE
Linux support

### PR DESCRIPTION
**Pull request by tklengyel**
Adding scaffolding to support Linux. Plugin support is only syscalls / cpuidmod / debugmon. KASLR not yet supported.

### CODE REVIEW

**Comment by Preetixen** [comment]
Hi

With reference to #226, can you please provide the commands and instructions for Linux syscall trapping for required programs as provided in https://drakvuf.com/ for windows syscalls.

Thanks

**Comment by Preetixen** [comment]
Also if you can please provide any information regarding the linux syscall trapping working mechanism..

**Comment by tklengyel** [comment]
It works exactly the same way as it works for Windows. You specify the rekall profile and the domain and it will start monitoring syscalls.

**Comment by Preetixen** [comment]
Okie Thanks for reply.. I think for ubuntu we have system.map file which provides the logical addresses for all kernel functions to be trapped...so can't we use it for addresses instead of rekall profile.

**Comment by Preetixen** [comment]
ALso, In windows drakvuf provides the support of tracing of windows 7 syscalls....In linux which particular distro is supports..?

**Comment by tklengyel** [comment]
The rekall profile includes the values from the system.map as well.

**Comment by Preetixen** [comment]
FOr windows, FS and GS register are used which points to _KPCR structure...nd some RVA and vCPU registers are used...something like that given in your paper...

How does it actually happen in Linux. Can you please exaplain....that address calculation part..so that you would have been able to insert break points at those kernel addresses.

Secondly, does darkvuf applicable to all windows versions and all linux versions for syscall tracing?

**Comment by Preetixen** [comment]
I have a few set of questions. Please take time to answer them. I will be very thankful to you:

For windows, 
LibVMI win guid tool is used to create the PDB file with associated GUID information
2. Rekall uses plugin to create the rekall profile by supplying the step 1 information and creates JSON format.

Question 1 : What is the case in Linux?.  As we can not create PDB file..there will be a different file like DWARF file, which tool is used for this and how all commands will look like now??

Question 2: What is this JSON file. If it contains all kernel symbols and logical addresses? How DRAKVUF is retrieving the physical addresses for windows and linux?

Question 3: Can DRAKVUF be used for all versions of windows and Linux

Question 4: Please explain this part : FS and GS register are used which points to _KPCR structure...nd some RVA and vCPU registers are used...something like that given in your paper...
Does this address calculation is used by DRAKVUF by reading the JSON file for windows as input?
How to calculate addresses for linux using JSON file.

**Comment by tklengyel** [comment]
1. See instructions on drakvuf.com or ask about Rekall internals on Rekall mailinglist/github page.
2. The Rekall profile is a collection if data about the kernel, constant symbols, structures and their layouts. The rest of the questions don't really make sense.
3. While some plugins would work for any operating systems (cpuid/debugmon), currently only Windows 7 is supported. Linux system call tracing will work for all versions, although you need KASLR disabled for now.
4. Yes, the offsets to calculate where the KPCR is in comparison to the Windows kernel base address is gathered from the Rekall profile. What address do you want to calculate on Linux?

**Comment by Preetixen** [comment]
Thanks for reply..If i asked something weird..I am just learning phase..

Clarfying question 4:
Symbol table (rekall profiles) which tells about the symbol name and their virtual addresses...
Now DRAKVUF is using the rekall profiles. How it is retrieving the actual physical addresses of kernel symbols in memory.
I got the following information from stack flow for same question:
To find out where these symbols are loaded in the main memory, subtract PAGE_OFFSET from the symbol address to get the offset and add this offset to the starting physical address of the kernel in the physical memory as determined from the system memory map.

i) My question is for Windows you have mentioned:  how you are calculating the offsets using the rekall profile. Are you using a  fixed Windows kernel base address value which you will be adding with the offsets for each kernel symbol. 

ii) FOr linux, how to calculate the page offsets. How to do we know the value of PAGE_OFFSET and starting base address of kernel. Are these values fixed?

Thanks

**Comment by tklengyel** [comment]
You just translate the virtual address to the physical address. For WIndows you can't use a fixed start address as it has KASLR, that's why you use the KPCR's RVA to find the virtual address first.

**Pull request merged**
