### PR TITLE
Deduplicate dll hooking code

### PR DESCRIPTION
**Pull request by disaykin**

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by disaykin** [comment]
@tklengyel I fixed the installation of the dependencies when building the container-compile stage.

**Comment by disaykin** [comment]
`  CC      pc-bios/optionrom/pvh_main.o
  BUILD   pc-bios/optionrom/multiboot.img
ld: Error: unable to disambiguate: -no-pie (did you mean --no-pie ?)
make[1]: *** [Makefile:53: multiboot.img] Error 1
make: *** [Makefile:576: pc-bios/optionrom/all] Error 2
make: *** Waiting for unfinished jobs....
make: Leaving directory '/__w/drakvuf/drakvuf/xen/tools/qemu-xen-build'`

**Comment by tklengyel** [comment]
@disaykin That's safe to ignore, probably just a compiler update that broke the Xen build in the rolling Ubuntu image.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by disaykin** [comment]
@tklengyel Can you merge this request, or do I need to do something extra?

**Comment by tklengyel** [comment]
LGTM but would like a +1 from the libusermode authors too

/cc @icedevml @chivay @BonusPlay

**Review by BonusPlay — APPROVED** [review]
:+1: just cleanup changes

**Pull request merged**
