### PR TITLE
Procmon printers

### PR DESCRIPTION
**Pull request by skvl**

### CODE REVIEW

**Comment by skvl** [comment]
@drakvuf-jenkins Retest this please

**Comment by icedevml** [comment]
@drakvuf-jenkins Retest this please.

**Comment by skvl** [comment]
@icedevml, I have tested this with Windows 10 1803 x64. It works. What's the issue with Jenkins?

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please.

**Pull request merged**
