### PR TITLE
win_injector: seperate createprocess method

### PR DESCRIPTION
**Pull request by manorit2001**
Related https://github.com/tklengyel/drakvuf/issues/936

Although, this method was split across x86 and x64 `if` paths separately, but they seemed similar only to me so I've combined them. Let me know if you think that is a mistake

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by manorit2001** [comment]
> 1635691083.439574 DRAKVUF v0.8-git20211031022202+1e1f9826-1 Copyright (C) 2014-2021 Tamas K Lengyel
GSlice: MemChecker: attempt to release non-allocated block: 0x55679ea34000 size=56
timeout: the monitored command dumped core

@tklengyel I don't understand this error. Also, I haven't changed anything related to Linux so how is this failing?

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by manorit2001** [comment]
Seems like the issue is being triggered in DRAKVUF part ( I haven't changed any code related to it ). I ran the `injector` on Win 7 x64 multiple times and it seemed to inject properly everytime. But whenever I run drakvuf with `-m createproc`. It sometimes runs properly but otherwise
- the injection happens successfully
- the plugins start but later, `SEGFAULT` occurs in `drakvuf_loop`

<details>
<summary>Enabled only syscall plugin</summary>

```
[...]
Injected PID: 1768. TID: 864                                                                                                                                                                  
Waiting for injected process                                                                                                                                                                  
1635752407.387283 Switching altp2m and to singlestep on vcpu 1                                                                                                                                
1635752407.389576 reset trap on vCPU 1, switching altp2m 0->1                                                                                                                                 
1635752407.390759 CR3 cb on vCPU 0: 0x187000                                                                                                                                                  
INT3 Callback @ 0x77299d5a. CR3 0x4a1ee000. vcpu 1. TID 1384                                                                                                                                  
Resume RAX: 0x1                                                                                                                                                                               
Resume successful                                                                                                                                                                             
1635752407.395691 Switching altp2m and to singlestep on vcpu 1                                                                                                                                
1635752407.398383 reset trap on vCPU 1, switching altp2m 0->1                                                                                                                                 
1635752407.399426 CR3 cb on vCPU 0: 0x5cc2f000                                                                                                                                                
1635752407.400309 CR3 cb on vCPU 0: 0x187000                                                                                                                                                  
1635752407.407641 CR3 cb on vCPU 1: 0x2d57b000                                                                                                                                                
Process start detected 1768 -> 0x2d57b000                                                                                                                                                     
1635752407.408001 DRAKVUF polling loop finished                                                                                                                                               
Finished injection loop                                                                                                                                                                       
[INJECT] TIME:1635752407.408226 METHOD:CreateProc  STATUS:SUCCESS PID:1296 FILE:"" ARGUMENTS:"" INJECTED_PID:1768 INJECTED_TID:864                                                            
Finished with injection. Ret: 2.                                                                                                                                                              
Injector freed
1635752407.408327 Enabling context based interception.
1635752407.408391 Starting plugins
1635752407.408577 Starting plugin syscalls
1635752407.409084 Kernel base: 0xfffff8000285c000
1635752407.409084 Kernel pagetable: 0x187000
1635752407.409412 NtBuildNumber: 7601
1635752407.409433 NT syscall table: 0xfffff800028f4300. Limit: 402
1635752407.409480 Win32k syscall table: 0xfffff96000185e00. Limit: 827
1635752407.409523 Windows syscall entry: 0xfffff800028fe9de
[...]
```

</details>

<details>
<summary>gdb</summary>

```
[SYSCALL] TIME:1635752408.156806 VCPU:1 CR3:0x2D57B000 "\Device\HarddiskVolume2\Windows\System32\calc.exe":NtOpenFile SessionID:1 PID:1768 PPID:1296 Module:"nt" vCPU:1 CR3:0x2D57B000 Syscall:48 NArgs:6 FileHandle:0xFFFFF880044927A0 DesiredAccess:0x80100000 ObjectAttributes:"\SystemRoot\Prefetch\CALC.EXE-77FDF17F.pf" IoStatusBlock:0xFFFFF880044927A8 ShareAccess:0x0 OpenOptions:0x20
1635752408.161689 Breakpoint VA 0xfffff80002d15331 -> PA 0x2d15331
1635752408.161850 Physmap populated? 0
1635752408.162249 Copied trapped page to new location
1635752408.162389 Activating remapped gfns in the altp2m views!
1635752408.162780               Trap added @ PA 0x2d15331 RPA 0xff0e0331 Page 11541 for NtOpenFile.
1635752408.162872 Switching altp2m and to singlestep on vcpu 1
1635752408.163478 reset trap on vCPU 1, switching altp2m 0->1
[SYSRET] TIME:1635752408.165666 VCPU:1 CR3:0x2D57B000 "\Device\HarddiskVolume2\Windows\System32\calc.exe":NtOpenFile SessionID:1 PID:1768 PPID:1296 Module:"nt" vCPU:1 CR3:0x2D57B000 Syscall:48 Ret:3221225524 Info:STATUS_OBJECT_NAME_NOT_FOUND
1635752408.165666 Removing breakpoint trap from 0x2d15331.
1635752408.170955 Removed memtrap for GFN 0x2d15 in altp2m view 1
1635752408.171089 Removed memtrap for GFN 0xff0e0 in altp2m view 1

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000021 in ?? ()
(gdb) bt
#0  0x0000000000000021 in ?? ()
#1  0x00005555555ff974 in int3_cb (vmi=<optimized out>, event=0x55555583fd38) at vmi.c:699
#2  0x00007ffff7f67ca5 in process_software_breakpoint (vmi=0x555555841ea0, vmec=0x7fffffffd4f0) at libvmi/driver/xen/xen_events.c:697
#3  0x00007ffff7f66203 in process_requests_7 (vmi=0x555555841ea0, requests_processed=0x7fffffffd7b0) at libvmi/driver/xen/xen_events.c:3031
#4  0x00007ffff7f672bf in xen_events_listen (vmi=0x555555841ea0, timeout=<optimized out>) at libvmi/driver/xen/xen_events.c:3273
#5  0x00005555555ffdff in drakvuf_vmi_event_callback (fd=<optimized out>, data=<optimized out>) at vmi.c:1547
#6  0x00005555555fbc3e in drakvuf_poll (drakvuf=drakvuf@entry=0x55555583fa90, timeout=timeout@entry=1000) at vmi.c:1580
#7  0x00005555555fff0d in drakvuf_loop (drakvuf=0x55555583fa90, is_interrupted=0x5555555f62c0 <is_interrupted(drakvuf*, void*)>, data=0x0) at vmi.c:1593
#8  0x00005555555f6266 in drakvuf_c::loop (this=0x555555827c00, duration=<optimized out>) at drakvuf.cpp:265
#9  0x00005555555f4820 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:940
(gdb) frame 1
#1  0x00005555555ff974 in int3_cb (vmi=<optimized out>, event=0x55555583fd38) at vmi.c:699
699                 rsp |= trap_info.trap->cb(drakvuf, &trap_info);
```

</details>

Do you have any idea why it might occur?

**Comment by manorit2001** [comment]
Hi, Could you give me some more info on `injector->break_loop_on_detection` flag? I think I know where the fault might have occurred

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by manorit2001** [comment]
I think `x86` injection control path will need some debugging from my side. I will look into it. If you could merge https://github.com/tklengyel/drakvuf-ci/pull/4. I think it might give me more insights on where it is failing

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
