### PR TITLE
Add `ZwWaitForSingleObject()' injection for asynchronous files

### PR DESCRIPTION
**Pull request by skvl**
Reading such files result in `STATUS_PENDING'.

### CODE REVIEW

**Comment by skvl** [comment]
@tklengyel I didn't touch `socketmon.cpp`! Though Travis CI banned me on it!

**Comment by tklengyel** [comment]
@skvl No worries, the astyle check has been bugging out on Travis lately, safe to ignore.

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test.

**Comment by tklengyel** [comment]
Looks good, thanks!

**Comment by tklengyel** [comment]
Coverity found this error but I'm not actually seeing why it thinks the array is being overrun. @skvl thoughts?

```
*** CID 191116:  Memory - corruptions  (OVERRUN)
/src/plugins/filedelete/filedelete2.cpp: 322 in readfile_cb(drakvuf *, drakvuf_trap_info *)()
316             uint64_t null64 = 0;
317     
318             init_argument(0, &args[0], ARGUMENT_INT, sizeof(uint64_t), (void*)injector->handle);
319             init_argument(0, &args[1], ARGUMENT_INT, sizeof(uint64_t), (void*)null64);
320             init_argument(0, &args[2], ARGUMENT_INT, sizeof(uint64_t), (void*)null64);
321     
>>>     CID 191116:  Memory - corruptions  (OVERRUN)
>>>     Overrunning array "args" of 72 bytes by passing it to a function which accesses it at byte offset 72.
322             if ( !setup_stack_64(vmi, info, &ctx, args, 3) )
323                 goto err;
324     
325             info->regs->rip = f->waitobject_va;
326     
327             injector->bp->name = "WaitForSingleObject ret";

**Comment by skvl** [comment]
@tklengyel sorry for late response. I have found this snippet in `setup_stack_64()`:
```
        // p1
        info->regs->rcx = args[0].data_on_stack;
        // p2
        info->regs->rdx = args[1].data_on_stack;
        // p3
        info->regs->r8 = args[2].data_on_stack;
        // p4
        info->regs->r9 = args[3].data_on_stack;
```

So it assumes that there is always 4 arguments. But in my case there is only 3.

Long live the *Coverity*!
Hooray *Coverity*!

**Pull request merged**
