### PR TITLE
fileextractor: algorithm modification and refactoring

### PR DESCRIPTION
**Pull request by EscardosS**
Main feature - files are now extracted along with NtWriteFile call.

New algorithm:
1. After first `NtWriteFile` plugin extract file or create empty;
2. The file is then updated with information from the following `NtWriteFile` calls.

Plugin calculates sha256 hashsum of extracted files.
Not closed files by the end of the analysis are also extracted from the system.
Also plugin was refactored.

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
> Plugin will not start without -D parameter 

The plugin should not halt the start of `drakvuf` in that case, especially since it didn't before. Printing a debug message would be sufficient.

**Comment by EscardosS** [comment]
I got an error even though the plugin was not running:

https://ci.drakvuf.com/job/DRAKVUF-windows7-sp1-x64/1112/console

**Comment by tklengyel** [comment]
Thanks!

**Pull request merged**
