### PR TITLE
Fixed premature exit before plugin stop functionality was triggered

### PR DESCRIPTION
**Pull request by disaykin**

### CODE REVIEW

**Comment by tklengyel** [comment]
Seems to trigger Valgrind warnings with `Conditional jump or move depends on uninitialised value(s)` in some plugins now.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by disaykin** [comment]
@tklengyel I sent some MRs with fixes of memory leaks in numerous places

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by disaykin** [comment]
@tklengyel Test was not triggered

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
