### PR TITLE
include config.h in libinjector

### PR DESCRIPTION
**Pull request by manorit2001**
I am having some troubles with these if defines locally, just testing the same hypothesis on the ci

FIXES: 
- Refactor in https://github.com/tklengyel/drakvuf/pull/754
- Includes `config.h` in `libinjector/private.h`

### CODE REVIEW

**Comment by manorit2001** [comment]
@tklengyel why isn't `ENABLE_DOPPELGANGING` being passed onto the files in libinjector? The `#define` only seems to be available in `src/injector.c` but not in `src/libinjector/injector.c` or other such files

**Comment by tklengyel** [comment]
Probably just need to include config.h in libinjector's private.h

**Comment by manorit2001** [comment]
Wow, this code seems to be broken from a really long time. The refactor for this function was done in b082a337844bab145317c2a40ac9d4982382b133

**Comment by tklengyel** [comment]
The doppleganging code can be removed entirely now, its been superseded by the writefile method.

**Pull request closed without merging**
