### PR TITLE
Add possibility of disabling sysret plugin

### PR DESCRIPTION
**Pull request by disaykin**
I tried to make disabling sysret functionality very similar to the functionality of disabling other plugins.

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
I don't particularly like pretending monitoring of sysrets is a separate plugin. Why not just have an otparg value that can be used to disable it?

**Comment by disaykin** [comment]
I rework PR, adding `--disable-sysret` option.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
