### PR TITLE
procmon: fix protection attributes

### PR DESCRIPTION
**Pull request by skvl**
* _autotools_'s `MAKE_TESTS` and [check](https://libcheck.github.io/check/) are used for unit-testing as in _LibVMI_.
* unit-test for _procmon_ plug-in been added to check `stringify_protection_attributes` function.
* Error in bits handling been fixed. The error been introduced in 8dbce1377db3a9bb69666ceaf7bad6efbdf134c7 .

### CODE REVIEW

**Comment by tklengyel** [comment]
What's the error in bit handling? AFAICT the macro does the same thing

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by skvl** [comment]
> What's the error in bit handling? AFAICT the macro does the same thing

No. The code:
```c++
        uint32_t attr = VMI_GET_BIT(attributes, i);
```
, returns `0` or `1`. Just the bit value at position `i`. E.g. for `attributes = 0x41` this returns `1` for `i = 6`.

The code:
```c++
        uint32_t attr = attributes & (1UL << i);
```
, returns masked value of attributes. E.g. for `attributes = 0x41` this returns `0x40` for `i = 6`.

**Comment by tklengyel** [comment]
Ah yes, there is `VMI_BIT_MASK` for that

**Pull request merged**
