### PR TITLE
injector: fix register restoring

### PR DESCRIPTION
**Pull request by icedevml**
related #925

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by icedevml** [comment]
@drakvuf-jenkins Retest this please.

**Comment by tklengyel** [comment]
I see that I indeed missed copying the saved regs, however this seems to be causing an issue when the injection is done via `drakvuf` and not the injector. The VM bluescreens. I disabled that test now just to see if it works otherwise.

**Comment by icedevml** [comment]
This PR only affects injection methods other than `createproc` (because it doesn't get through this code path, AFAIK). But I think it affects both `drakvuf` and `injector` programs.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please.

**Comment by tklengyel** [comment]
The win7 sp1 x64 test currently does a test-run with the injector with both `-m createproc` and `-m shellexec`, followed by an injection with the main `drakvuf` using `createproc`. I've added a `sleep 5` between the injector tests and running drakvuf, that seems to have stabilized things.

**Comment by icedevml** [comment]
:concerned: But it looks like it worked now.

**Pull request merged**
