### PR TITLE
filedelete: switch to new printing API

### PR DESCRIPTION
**Pull request by skvl**

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by skvl** [comment]
@tklengyel what is the error with Windows 10 2004? I don't understand the output...

**Comment by tklengyel** [comment]
I'm using the box for some other stuff and there wasn't enough RAM for the CI to spin up that VM. I'll retest this when the box is free again.

**Comment by skvl** [comment]
Thank you!

**Comment by skvl** [comment]
@tklengyel could you ask @drakvuf-jenkins retest this please.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
