### PR TITLE
LIBRARYMON plugin: Trace library loads

### PR DESCRIPTION
**Pull request by sifurov**

### CODE REVIEW

**Comment by tklengyel** [comment]
Could you please provide a description of the plugin you are adding and also what the new `plugins_ex` addition does?

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by sifurov** [comment]
librarymon is a plugin that print a parameters of call function LdrLoadDll and LdrGetDllHandle (for this moment).

The class plugin_ex is a smart wrapper for common plugin operations like that registration a trap in exe, in dll and at end of function. The management a list of that traps (automatically deletion).

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
Thanks, looks good!

**Pull request merged**
