### PR TITLE
part of plugins is refactored to use new printing api

### PR DESCRIPTION
**Pull request by zodeak**
Refactoring plugins output to use new printing api.

### CODE REVIEW

**Comment by icedevml** [comment]
This would need some very extensive testing against DRAKVUF Sandbox to ensure that it doesn't break anything. I'm going to do it within few days.

**Comment by icedevml** [comment]
Since there are compile errors right now, I will wait until the CI is passing.

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
Thank you for this PR, it makes the code so much cleaner 👍

**Comment by zodeak** [comment]
What is the problem with default? Details cannot be viewed.

**Comment by tklengyel** [comment]
Valgrind errors:
```
Use of uninitialised value of size 8
Uninitialised value was created by a stack allocation

/shared/jenkins/DRAKVUF-build/src/plugins/./output_format/deffmt.h:163
 163         os << (data.withbase ? "0x" : "") << std::uppercase << std::hex << data.value;
```

and
```

Conditional jump or move depends on uninitialised value(s)
Uninitialised value was created by a stack allocation

/shared/jenkins/DRAKVUF-build/src/plugins/./output_format/deffmt.h:163
 163         os << (data.withbase ? "0x" : "") << std::uppercase << std::hex << data.value;

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by zodeak** [comment]
valgind again?
how is it been runned? i need to understand problem.

**Comment by icedevml** [comment]
@drakvuf-jenkins Retest this please.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please.

**Comment by tklengyel** [comment]
Valgrind reports:

```
Use of uninitialised value of size 8
/shared/jenkins/DRAKVUF-build/src/plugins/./output_format/deffmt.h:164

159     template <class Tv = T>
160     static bool print(std::ostream& os, const fmt::Xval<Tv>& data, char)
161     {
162         auto ff = os.flags(); 163         auto base = data.withbase ? "0x" : "";
164         os << base << std::uppercase << std::hex << data.value;

**Comment by tklengyel** [comment]
Also
```
Invalid read of size 1
Address 0x0 is not stack'd, malloc'd or (recently) free'd

/shared/jenkins/DRAKVUF-build/src/plugins/./output_format/deffmt.h:301
 301         procname += info->attached_proc_data.name;
```

**Comment by zodeak** [comment]
@tklengyel **default** waiting for status for hours

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
I had to take the CI box offline to test something else.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
FYI the CI system is going to be offline for a while. I recommend setting up a local test environment for development.

**Comment by zodeak** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@zodeak This looks good to me, are you finished with it?

**Comment by zodeak** [comment]
Yes, i've finished.
The rest of plugins will be done in separate mr commits.

**Pull request merged**
