### PR TITLE
Codemon refactor

### PR DESCRIPTION
**Pull request by BonusPlay**
Refactor big part of codemon. Migrate traps to RAII managed hooks, implement page faulting for vmi_extended_lookups and more fixups. Not everything is yet ported, but it's a start.

This is a "RFC" PR, I want to finish running local tests before merge.

### CODE REVIEW

**Comment by BonusPlay** [comment]
@tklengyel could we run this PR on drakvuf-ci ? It does seem to be working locally.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by tklengyel** [comment]
Plugin codemon startup failed!

**Comment by BonusPlay** [comment]
Interesting. Could you send me debug logs or command line? It does work on local setup with drakvuf-sandbox. I may have introduced some kind of API break with some parameter now being required even tho it wasn't previously. I'd gladly fix the issue.

**Comment by BonusPlay** [comment]
This also closes #1121 as page faulting was implemented in this PR.

**Comment by BonusPlay** [comment]
@tklengyel bump?

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by BonusPlay** [comment]
@tklengyel this should do it. For some reason CI seems to be down tho.

**Comment by tklengyel** [comment]
`[CODEMON] Output directory for dumps not provided, not activating codemon plugin`, should gracefully exit at this point instead of stopping the start-up

**Comment by BonusPlay** [comment]
That's exactly what last commit does.
```c
    //Check if the dump directory parameter was provided
    if (!config->dump_dir)
    {
        fprintf(stderr, "[CODEMON] Output directory for dumps not provided, not activating codemon plugin\n");
        return;
    }
```

**Comment by tklengyel** [comment]
In that case there seems to be some regression. Could you also rebase on the latest HEAD?

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by BonusPlay** [comment]
The build is failing, because CI expects hardcoded 1 line of output: https://github.com/tklengyel/drakvuf-ci/blob/b887c32c64fcf543004d9a68e15963b18fa13236/run.sh#L341. I could replace `fprintf(stderr` with `PRINT_DEBUG` but that's kind-of counter intuitive for end user.

**Comment by tklengyel** [comment]
Not counter-intuirive, other plugins do the same when they skip their startup because of insufficient inputs provided. Or just don't print to stderr.

**Comment by BonusPlay** [comment]
@tklengyel can I ask for a CI re-run?

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
