### PR TITLE
Universal function to set the stack

### PR DESCRIPTION
**Pull request by mdolmen**
Ease the process of adding a new Windows API function support.

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by mdolmen** [comment]
I can't access to Jenkins details..

**Comment by tklengyel** [comment]
@mdolmen that's ok, Jenkins has been finicky lately. Could you make sure your branch is up-to-date with the current master branch?

**Comment by tklengyel** [comment]
So the problem Jenkins is having with this PR is that doing multiple injections in the row fail. Could you check on your side whether you can reproduce that problem?

**Comment by mdolmen** [comment]
Ok I'll try

**Comment by mdolmen** [comment]
I must have done something wrong with my commits at some point, some of them which are in my experimenting branch was present to master too..

**Comment by mdolmen** [comment]
Multiple injections in a row is working on my machine, for both shellexec and createproc.

**Comment by tklengyel** [comment]
This looks good and does work when I tested manually. However, for merging we will also need 32-bit support.

**Comment by mdolmen** [comment]
Ok I'll work on that then.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please.

**Comment by tklengyel** [comment]
@mdolmen very nice! Looks good, passes the tests :) Good job!

**Comment by mdolmen** [comment]
Perfect! Thanks :)

**Pull request merged**
