### PR TITLE
libusermode: fix WoW64 unicode printing

### PR DESCRIPTION
**Pull request by skvl**
Re-work #931

### CODE REVIEW

**Comment by icedevml** [comment]
@drakvuf-jenkins This is OK to test.

**Comment by tklengyel** [comment]
@skvl This will need a rebase before I can merge

**Comment by skvl** [comment]
@tklengyel, done.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by skvl** [comment]
@tklengyel what's the error?

**Comment by icedevml** [comment]
@drakvuf-jenkins Retest this please.

**Comment by icedevml** [comment]
:thinking:

```
Running DRAKVUF #2 for 60 seconds. Opts:  -S /shared/jenkins/workspace/DRAKVUF-windows10-2004/ci/syscalls.txt -a syscalls
DRAKVUF is running with PID 12111, background pid is 12098
CPU utilization average: 7
Exit status: 0
stderr line count: 1
Syscalls: 13039
/shared/drakvuf-ci/run.sh: line 369: scalls.txt: command not found
Overhead is a lot
```

**Comment by tklengyel** [comment]
I'm tweaking the CI, hold on.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
