### PR TITLE
libusermode: add pulonglong type to print 8 byte values from pointers

### PR DESCRIPTION
**Pull request by skvl**

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by skvl** [comment]
@tklengyel i believe that the [error](https://ci.drakvuf.com/job/DRAKVUF-windows7-sp1-x64/796/console) doesn't relate to the PR.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
