### PR TITLE
FILEDELETE: Print sequence numbers

### PR DESCRIPTION
**Pull request by disaykin**
This allows correlate file artifacts and filedelete logs.

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by disaykin** [comment]
This MR based on #497

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by disaykin** [comment]
Rebased to master

**Comment by disaykin** [comment]
@tklengyel is astyle configuration broken? Or I need fix the code accoding its recommendations?

**Comment by tklengyel** [comment]
Try to run astyle locally and see if you get the same changes as on Travis. The git diff definitely has some parts that look odd on Travis.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
