### PR TITLE
Procmon fix multiple issues

### PR DESCRIPTION
**Pull request by skvl**

### CODE REVIEW

**Comment by skvl** [comment]
@tklengyel @icedevml could you ask @drakvuf-jenkins retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by skvl** [comment]
@tklengyel is this (https://ci.drakvuf.com/job/DRAKVUF-windows10/251/console) out of resources error?

```
+ sudo -E /shared/drakvuf-ci/run.sh windows10 /shared/jenkins/workspace/DRAKVUF-windows10 /opt/libvmi RESET
Running environment reset..
Reset result: 32:error:error:error
```

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by skvl** [comment]
@tklengyel this time goes better: https://ci.drakvuf.com/job/DRAKVUF-PR/247/ . Only two tests fails.

**Comment by skvl** [comment]
@tklengyel @icedevml I could split this PR into 3 smaller.

**Comment by skvl** [comment]
Have been splat into #977 , #978 , #979

**Pull request closed without merging**
