### PR TITLE
syscalls: print _OBJECT_ATTRIBUTES

### PR DESCRIPTION
**Pull request by skvl**
Re-work #931

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
@skvl This is the PR that causes the valgrind issues. I recommend you test it locally with valgrind (https://github.com/tklengyel/valgrind/tree/xen_4.14) and with a libxc that has some extra initialization that makes valgrind more happy (https://github.com/tklengyel/xen/tree/xc_stack_zero)

**Comment by skvl** [comment]
@tklengyel, I have found an error. Thank you!

-----
*Note* I have tried to enable ASan with `--enable-sanitize` and faced the error with libtool (though I think so). See [SO](https://stackoverflow.com/a/33221551)

**Comment by skvl** [comment]
@tklengyel, what's the error?

Jenkins [doesn't show](https://ci.drakvuf.com/job/DRAKVUF-windows7-sp1-x64/191/valgrindResult/pid=29468,0x17/) source code lines causing the errors.

In my tests there is no errors with the branch:
```
==27736== Memcheck, a memory error detector
==27736== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==27736== Using Valgrind-3.16.0.GIT and LibVEX; rerun with -h for copyright info
==27736== Command: /home/skovalev/src/drakvuf-gh/src//drakvuf -d trap -r /home/skovalev/win10-1803-x64@0/volatility3/kernel.json -x delaymon -t 5 -o kv
==27736== 
1597396510.190471 DRAKVUF v0.8-git20200814101131+84bcc94-1 Copyright (C) 2014-2020 Tamas K Lengyel
==27736== Warning: noted but unhandled ioctl 0x50ff with no size/direction hints.
==27736==    This could cause spurious value errors to appear.
==27736==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==27736== Warning: noted but unhandled ioctl 0x105005 with no size/direction hints.
==27736==    This could cause spurious value errors to appear.
==27736==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==27736== Syscall param XEN_DOMCTL_vm_event_op u.vm_event_op_00000012.u.enable points to uninitialised byte(s)
==27736==    at 0x6CF76D7: ioctl (syscall-template.S:78)
==27736==    by 0x609F1A4: xencall1 (in /usr/lib/x86_64-linux-gnu/libxencall.so.1.2)
==27736==    by 0x5C8C490: xc_vm_event_control (in /usr/lib/x86_64-linux-gnu/libxenctrl.so.4.13.0)
==27736==    by 0x5C8C7BB: xc_vm_event_enable (in /usr/lib/x86_64-linux-gnu/libxenctrl.so.4.13.0)
==27736==    by 0x4E4CEE9: xen_init_events (xen_events.c:3108)
==27736==    by 0x4E455CA: xen_init_vmi (xen.c:650)
==27736==    by 0x4E58DB1: vmi_init (core.c:580)
==27736==    by 0x16779D: init_vmi (vmi.c:1441)
==27736==    by 0x161692: drakvuf_init (drakvuf.c:199)
==27736==    by 0x15F1DD: drakvuf_c::drakvuf_c(char const*, char const*, char const*, output_format_t, bool, bool, bool, unsigned long) (drakvuf.cpp:174)
==27736==    by 0x15E6E7: main (main.cpp:552)
==27736==  Address 0x402b028 is in a rw- mapped file /dev/xen/hypercall segment
==27736== 
==27736== Syscall param XEN_DOMCTL_vm_event_op u.vm_event_op_00000012.u.enable points to uninitialised byte(s)
==27736==    at 0x6CF76D7: ioctl (syscall-template.S:78)
==27736==    by 0x609F1A4: xencall1 (in /usr/lib/x86_64-linux-gnu/libxencall.so.1.2)
==27736==    by 0x5C8C9C9: xc_vm_event_get_version (in /usr/lib/x86_64-linux-gnu/libxenctrl.so.4.13.0)
==27736==    by 0x4E4D15F: xen_init_events (xen_events.c:3212)
==27736==    by 0x4E455CA: xen_init_vmi (xen.c:650)
==27736==    by 0x4E58DB1: vmi_init (core.c:580)
==27736==    by 0x16779D: init_vmi (vmi.c:1441)
==27736==    by 0x161692: drakvuf_init (drakvuf.c:199)
==27736==    by 0x15F1DD: drakvuf_c::drakvuf_c(char const*, char const*, char const*, output_format_t, bool, bool, bool, unsigned long) (drakvuf.cpp:174)
==27736==    by 0x15E6E7: main (main.cpp:552)
==27736==  Address 0x402b028 is in a rw- mapped file /dev/xen/hypercall segment
==27736== 
==27736== Conditional jump or move depends on uninitialised value(s)
==27736==    at 0x4E4756A: xen_start_single_step (xen_events.c:321)
==27736==    by 0x4E599CC: driver_start_single_step (driver_wrapper.h:500)
==27736==    by 0x4E599CC: register_singlestep_event (events.c:379)
==27736==    by 0x167A7E: init_vmi (vmi.c:1517)
==27736==    by 0x161692: drakvuf_init (drakvuf.c:199)
==27736==    by 0x15F1DD: drakvuf_c::drakvuf_c(char const*, char const*, char const*, output_format_t, bool, bool, bool, unsigned long) (drakvuf.cpp:174)
==27736==    by 0x15E6E7: main (main.cpp:552)
==27736== 
==27736== Conditional jump or move depends on uninitialised value(s)
==27736==    at 0x4E4C92F: xen_set_int3_access (xen_events.c:271)
==27736==    by 0x4E59686: driver_set_intr_access (driver_wrapper.h:468)
==27736==    by 0x4E59686: register_interrupt_event (events.c:185)
==27736==    by 0x16815E: init_vmi (vmi.c:1578)
==27736==    by 0x161692: drakvuf_init (drakvuf.c:199)
==27736==    by 0x15F1DD: drakvuf_c::drakvuf_c(char const*, char const*, char const*, output_format_t, bool, bool, bool, unsigned long) (drakvuf.cpp:174)
==27736==    by 0x15E6E7: main (main.cpp:552)
==27736== 
==27736== Syscall param XEN_DOMCTL_vm_event_op u.vm_event_op_00000012.u.enable points to uninitialised byte(s)
==27736==    at 0x6CF76D7: ioctl (syscall-template.S:78)
==27736==    by 0x609F1A4: xencall1 (in /usr/lib/x86_64-linux-gnu/libxencall.so.1.2)
==27736==    by 0x5C8C490: xc_vm_event_control (in /usr/lib/x86_64-linux-gnu/libxenctrl.so.4.13.0)
==27736==    by 0x4E4D612: xen_events_destroy (xen_events.c:3328)
==27736==    by 0x4E45799: xen_destroy (xen.c:683)
==27736==    by 0x4E58B02: driver_destroy (driver_wrapper.h:45)
==27736==    by 0x4E58B02: vmi_destroy (core.c:848)
==27736==    by 0x16887D: close_vmi (vmi.c:1741)
==27736==    by 0x1605D5: drakvuf_close (drakvuf.c:123)
==27736==    by 0x15F388: drakvuf_c::~drakvuf_c() (drakvuf.cpp:191)
==27736==    by 0x15ED9D: main (main.cpp:601)
==27736==  Address 0x402b028 is in a rw- mapped file /dev/xen/hypercall segment
==27736== 
==27736== 
==27736== HEAP SUMMARY:
==27736==     in use at exit: 48,634 bytes in 506 blocks
==27736==   total heap usage: 847,930 allocs, 847,424 frees, 518,743,195 bytes allocated
==27736== 
==27736== LEAK SUMMARY:
==27736==    definitely lost: 5,976 bytes in 249 blocks
==27736==    indirectly lost: 24,018 bytes in 249 blocks
==27736==      possibly lost: 0 bytes in 0 blocks
==27736==    still reachable: 18,640 bytes in 8 blocks
==27736==         suppressed: 0 bytes in 0 blocks
==27736== Rerun with --leak-check=full to see details of leaked memory
==27736== 
==27736== Use --track-origins=yes to see where uninitialised values come from
==27736== For lists of detected and suppressed errors, rerun with: -s
==27736== ERROR SUMMARY: 6 errors from 5 contexts (suppressed: 0 from 0)
```

**Comment by tklengyel** [comment]
@skvl `==27736==    definitely lost: 5,976 bytes in 249 blocks`

**Comment by skvl** [comment]
> @skvl `==27736== definitely lost: 5,976 bytes in 249 blocks`

Yes. I've seen the message. But there are no errors with `syscalls`. I think this from some other part.

**Comment by tklengyel** [comment]
>  But there are no errors with syscalls

I can't tell that based on the logs. Either way, if the PR triggers a path that reproducibly leaks now, even if its some other place, it needs to be fixed.

**Comment by skvl** [comment]
I have added `--leak-check=full` argument to _valgrind_ and managed to find a bug. Thank you.

**Pull request merged**
