### PR TITLE
Add Travis CI addon for SonarQube

### PR DESCRIPTION
**Pull request by skvl**
One should define SONAR_TOKEN variable in Travis CI project's settings.

-----
@tklengyel this patch defines new test in `.travis.yml` which requires a project named *drakvuf* on [SonarCloud](https://sonarcloud.io). You could see my [example](https://sonarcloud.io/project/issues?id=skvl-drakvuf&resolved=false&severities=BLOCKER&types=CODE_SMELL) project.

### CODE REVIEW

**Comment by tklengyel** [comment]
So if you turn the coverity scan token into a variable, where does it get set?

**Comment by skvl** [comment]
@tklengyel I don't understand the question. Do You mean the `$COVERITY_SCAN_TOKEN` from #450 ? You could set all tokens on project's settings page (i think [this](https://travis-ci.org/tklengyel/drakvuf/settings) should be Yours) in `Environment Variables` section.

**Comment by tklengyel** [comment]
According to https://docs.travis-ci.com/user/sonarcloud these need to be added t the travis.yml:

```
addons:
  sonarcloud:
    organization: "sonarcloud_organization_key" # the key of the org you chose at step #3
    token:
      secure: ********* # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner

**Comment by tklengyel** [comment]
Ah never mind, I see it's there :) Let's see if it goes through now.

**Comment by skvl** [comment]
Have You created a SonarQube project?

**Comment by skvl** [comment]
It looks like the `sonar` addon have not been applied. I have seen this when I first missaligned `.travis.yml`. But currently it aligned properly.

**Comment by skvl** [comment]
I think You have not set `SONAR_TOKEN`.

**Comment by skvl** [comment]
Compare Yours log:
```
[33;1mSetting environment variables from .travis.yml[0m
$ export TEST="SonarCloud"

$ export CC=clang
```
... and mine:
```
[33;1mSetting environment variables from repository settings[0m
$ export SONAR_TOKEN=[secure]

[33;1mSetting environment variables from .travis.yml[0m
$ export COVERITY_SCAN_TOKEN=[secure]
$ export TEST="SonarCloud"

$ export CC=clang
```

**Comment by tklengyel** [comment]
```
Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

**Comment by skvl** [comment]
Can You create a local branch on top of mine for test?

**Comment by tklengyel** [comment]
I have, read the link I posted. The problem is that for PRs coming from forks those secure tokens are not available. That's why it can't run. I have to manually encrypt the token so that it can be safely visible for PRs.

**Comment by skvl** [comment]
But it works with `COVERITY_SCAN_TOKEN`

**Comment by tklengyel** [comment]
No, it doesn't work with COVERITY_SCAN_TOKEN either, if you check the logs, the coverity token is only available for builds that are from within the repository. But the error there doesn't fail like the Sonar test does. Plus we only run coverity scans for the master branch anyway, so there it's fine. Here it's a blocker.

**Comment by tklengyel** [comment]
Manually encrypting the token and setting it as an environmental variable doesn't work either, it has to be in the file itself as
`secure: "Pdb1+p0R/KKvZydJdlqMv/9zQEGMPOwelmMdi9yrKppwJRHanCTDrZ6A2Be54o9ZOBxe4d1JFnyLh8YU52bAEaCy2mhzA8/1yWVHYSH54Tu+X/xlvPmyIiN1qOaNJbHHQYXqUTNOaKdmolk3UAKO4Kj+La9oke3ZTN5qVaNlEcs="`

**Comment by skvl** [comment]
You should not manually encrypt token! You should past original token into variable and Travis CI would secure it.

**Comment by skvl** [comment]
Read the [documentation](https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings).

**Comment by tklengyel** [comment]
That's what I did. It doesn't work for PRs.

**Comment by tklengyel** [comment]
Setting the manually encrypted token as a non-secure environmental variable doesn't work either.

**Comment by tklengyel** [comment]
Yea, the only way this is going to work is if the `secure: ...` line is in the Travis file itself.

**Comment by skvl** [comment]
But why I don't see something like this:
```
Setting environment variables from repository settings
$ export SONAR_TOKEN=[secure]

Setting environment variables from .travis.yml
$ export COVERITY_SCAN_TOKEN=[secure]
$ export TEST="SonarCloud"
```
in current logs?

Fill free to reject this PR. Sorry for inconvenience.

**Comment by tklengyel** [comment]
Because you are not reading the link I copied above: See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

**Comment by skvl** [comment]
From [here](https://travis-ci.org/tklengyel/drakvuf/jobs/416402548) I see that variables have been set:
```
Setting environment variables from repository settings
$ export SONAR_TOKEN=[secure]
$ export [secure]=[secure]
$ export COVERITY_PROJECT_NAME=tklengyel/drakvuf
$ export COVERITY_BRANCH_PATTERN=master
$ export COVERITY_SCAN_TOKEN=[secure]
Setting environment variables from .travis.yml
$ export TEST="Coverity"
```
... very strange ...

**Comment by tklengyel** [comment]
I do like the idea of hooking SonarQuest into the CI system but it needs to be done according to the Travis documentation so that it doesn't block PRs.

**Comment by tklengyel** [comment]
Because that build is _after_ the PR has been merged.

**Comment by tklengyel** [comment]
This is what the travis script needs to disable this test for PRs:
```
script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi'

**Comment by skvl** [comment]
So I have fixed this according to Your suggestion.

Though I have re-read the [documentation](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions):
```
Travis CI makes encrypted variables and data available only to pull requests coming from the same repository. These are considered trustworthy, as only members with write access to the repository can send them.
```

As I understand this means: Travis CI sets encrypted variables in per organization manner. Thus in my repository I have to define this variables with my tokens because I could not access Your tokens.

So I think that something is with settings.

**Comment by tklengyel** [comment]
What that means is that if I push a branch to drakvuf and open a PR for it, secure environmental variables will be available for it. But if you open a PR from a fork, they won't. It's not about the settings I have, it's the default Travis behavior.

**Comment by tklengyel** [comment]
Now that it is merged a build will be triggered on Travis which will have access to the SONAR_TOKEN. Let's see if it builds :)

**Comment by tklengyel** [comment]
Build running @ https://travis-ci.org/tklengyel/drakvuf/jobs/416435297

**Pull request merged**
