### PR TITLE
Refactor createSyscallHook. Make it OS polimorfic.

### PR DESCRIPTION
**Pull request by disaykin**

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by BonusPlay** [comment]
One small thing, I don't believe `const std::optional<std::string>& display_name` is a thing. Either to `std::optional<std::string>` or 
use [std::reference_wrapper](http://en.cppreference.com/w/cpp/utility/functional/reference_wrapper) (which I'm not a big fan of).

**Comment by disaykin** [comment]
@BonusPlay I pass an optional string by a reference. This is a normal use case.

**Comment by BonusPlay** [comment]
https://stackoverflow.com/questions/69277649/does-passing-an-stdoptionalt-by-reference-actually-save-copying

Pretty sure you use `std::optional<T>` in the same way you use `int` instead of `const int&`, since `std::optional` is a small type. Please point me to any piece of code that uses `std::optional<T>&`.

**Comment by BonusPlay** [comment]
Fair enough.

**Pull request merged**
