### PR TITLE
Use std::filesystem helper instead of direct include

### PR DESCRIPTION
**Pull request by chivay**
Ubuntu 18.04 ships with a compiler that exposes std::filesystem as an
experimental feature.
Use local helper file that handles that quirk.

Fixes: 851bcb8 Drakvuf write-file option (#1235)

### CODE REVIEW

**Comment by tklengyel** [comment]
I would prefer if that header was moved out from the plugins folder to the top. Also, its missing the license header so please add it.

**Review by BonusPlay — APPROVED** [review]

**Comment by chivay** [comment]
Sure, I'll fix it :)

**Comment by chivay** [comment]
Addressed both of these issues.

**Comment by icedevml** [comment]
@drakvuf-jenkins This is OK to test.

**Pull request merged**
