### PR TITLE
filetracer update

### PR DESCRIPTION
**Pull request by EscardosS**
filetracer update to get more information about system calls:

- [NtSetInformationFile](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntsetinformationfile) with `FileEndOfFileInformation` flag to get new size of a file
- [NtCreateFile](https://learn.microsoft.com/en-us/windows/win32/api/winternl/nf-winternl-ntcreatefile) `IoStatusBlock` to get final completion status (the status is correct only when the function returns success, otherwise not) - `FILE_SUPERSEDED` (0), `FILE_OPENED` (1) and etc.

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by EscardosS** [comment]
Looks like VM not started 

https://ci.drakvuf.com/job/DRAKVUF-windows10/917/console

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by EscardosS** [comment]
```
Injector starting calc.exe through PID 1984 TID: 0
[INJECT] TIME:1679864718.112969 METHOD:CreateProc STATUS:PrematureBreak
Process startup failed
```
https://ci.drakvuf.com/job/DRAKVUF-windows7-sp1-x64/1163/console

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by tklengyel** [comment]
Could you rebase this PR on the latest main? Looks mostly fine but a new CI check needs to pass before merging it.

**Comment by EscardosS** [comment]
Not on the first try, but I did it

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by tklengyel** [comment]
Thanks!

**Pull request merged**
