### PR TITLE
Add plugin to track and dump NtWriteVirtualMemory calls

### PR DESCRIPTION
**Pull request by alexmocha**
Implementation of the feature discussed in #650
This plugin logs and allows to dump the memory written by the NtWriteVirtualMemory system call.
The dump folder is chosen with the  ```--virtualmemdump ``` argument.

### CODE REVIEW

**Comment by icedevml** [comment]
Could this be a part of `memdump` plugin introduced in #652? It seems that the goal is very similiar.

I can potentially prepare a PR which would incorporate this into `memdump`.

**Comment by alexmocha** [comment]
@icedevml  Yes the goal is almost the same. I think it could be great to integrate this feature into ```memdump```.

**Comment by icedevml** [comment]
Ok, as `memdump` was merged, I will propose something soon.

**Comment by icedevml** [comment]
@alexmocha Do you have some hashes of (malware) samples for which this would produce interesting results?

**Pull request closed without merging**
