### PR TITLE
Added stack alignment and function putting string on stack for 32 bit Windows

### PR DESCRIPTION
**Pull request by nystilaps**
For 32 bit Windows:
Added stack and parameters allocated on stack alignment to 64 bytes.
Added function for putting string on stack with alignment to 64 bytes.

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by nystilaps** [comment]
I can't access ci.drakvuf.com, could you please give a hint why it fails to build?
On my machine locally everything build ok.

**Comment by tklengyel** [comment]
@nystilaps Jenkins just been finicky lately, I'm not sure why yet

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
This looks good to me, thanks!

**Pull request merged**
