### PR TITLE
libusermode: stop print addresses of string arguments

### PR DESCRIPTION
**Pull request by skvl**
This unifies the output of libusermode with other plugins where we print only values but no addresses

### CODE REVIEW

**Comment by skvl** [comment]
@tklengyel @icedevml I think this makes the output of _apimon_ more clear.

**Comment by icedevml** [comment]
IMHO sometimes pointers are also useful, especially when the string looks weird&corrupted.

Btw. sometimes there are some corrupted/uninitialized strings which result in printing some invalid characters, I think it would be good to change the string printing algorithm in such way that printable ASCII and basic UTF-16 would be printed literally and all the remaining characters would be printed as `\x12` etc. I've seen this in some other sandboxes and I think this format is a good compromise. It's both easy readable to humans and could be easily un-escaped programatically.

**Comment by skvl** [comment]
@icedevml do you think that we should add some extra argument to _drakvuf_ (e.g. `--libusermode-print-strings-without-addresses`)?

**Comment by icedevml** [comment]
@skvl seems OK to me

**Comment by skvl** [comment]
@icedevml done!

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by skvl** [comment]
@tklengyel @icedevml I've rebased the branch

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by skvl** [comment]
@tklengyel @icedevml I've rebased the branch

**Comment by skvl** [comment]
@tklengyel @icedevml what's the issue with the PR?

**Comment by tklengyel** [comment]
LGTM, would like a +1 from @icedevml as well since he had some requests on the PR earlier

**Comment by skvl** [comment]
@tklengyel I have got +1 from @icedevml already. Look comment https://github.com/tklengyel/drakvuf/pull/999#issuecomment-692786112

**Comment by tklengyel** [comment]
Well, a thumbs up is a bit ambiguous, I would prefer a written +1 :) I don't think there is any issue here so this is more of a formality just to make sure he is happy with all the changes.

**Comment by icedevml** [comment]
As there is a cmd line switch which would fall back to the old behaviour I assume it's OK; LGTM

**Comment by icedevml** [comment]
thanks for being extra cautious about this :)

**Pull request merged**
