### PR TITLE
memdump: disable memdump/userhook for Windows 10 1703

### PR DESCRIPTION
**Pull request by skvl**

### CODE REVIEW

**Comment by icedevml** [comment]
@skvl What problems are you experiencing with usermode hooking on Win10?

**Comment by tklengyel** [comment]
And why only with Windows build `15063`?

**Comment by skvl** [comment]
_libusermode/userhook.cpp_ hooks `MiCopyOnWrite`, which is not defined for _Windows 10 1703 x64_. Though there is `MiCopyOnWriteEx`.

**Comment by skvl** [comment]
@tklengyel I don't know. With build 1803 it works. Though I don't check it with previous builds.

**Comment by icedevml** [comment]
1703 seems to be fairly old build btw.

**Comment by skvl** [comment]
@icedevml, you are right. It is 3 years old. But I had to deal with it.

**Comment by tklengyel** [comment]
Perhaps then disable it for everything that's older then that, not just for that specific version?

**Comment by skvl** [comment]
@tklengyel, it is possible. Though I didn't check other versions. So I decided not to overkill. What you think?

**Comment by tklengyel** [comment]
I think it would be safer to disable it for older builds, doubt it would only be that one version where that function is missing. Probably got introduced in later builds only. In any case, if anyone needs it for older builds they can investigate whether it works or not.

**Comment by skvl** [comment]
@tklengyel done!

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Pull request merged**
