### PR TITLE
fileextractor: log stage switches and other events

### PR DESCRIPTION
**Pull request by skvl**
Based on https://github.com/tklengyel/drakvuf/pull/1779

### CODE REVIEW

**Comment by skvl** [comment]
@tklengyel , I have simplified the `fileextractor` plugin. Complexity checks passed.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by skvl** [comment]
@tklengyel , I've ported a forgotten bugfix into the branch.

Tasks should be removed on finish and error. This avoids confusion about register state restore. Thus less BSODs.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Pull request merged**
