### PR TITLE
BSOD monitor

### PR DESCRIPTION
**Pull request by skvl**
Allows to get notification of bug check (aka BSOD).

*NOTE* For some reason on _x86_ there is no notification. Debug in progress.

### CODE REVIEW

**Comment by skvl** [comment]
@tklengyel could You please check why _KeBugCheck_ hook doesn't work on _x86_.

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test.

**Comment by tklengyel** [comment]
@skvl what do you mean by the hook not working? If it doesn't get triggered it is likely because the entry point of `KeBugCheck` doesn't get called. Perhaps another function is used?

**Comment by skvl** [comment]
I have tested both _x64_ and _x86_ with [this](https://github.com/skvl/windows-examples) simple driver. So I really think that `KeBugCheck` is called. But on _x86_ it doesn't get triggered...

**Comment by tklengyel** [comment]
@skvl I would double check that you are hooking the right address. Print the address of `KeBugCheck` in that driver and compare with the address that got hooked by DRAKVUF.

**Comment by skvl** [comment]
@tklengyel You are brilliantly right!

But I don't understand what`s the deal.

From debug output:
```
[BSODMON] [KeBugCheckEx] RVA 0xdef02
        ntoskrnl.exe @ 0x82610000
Physmap populated? 0
Copied trapped page to new location
Activating remapped gfns in the altp2m views!
                Trap added @ PA 0x26eef02 RPA 0xff005f02 Page 9966 for KeBugCheckEx. 
[BSODMON] [KeBugCheck] RVA 0xdeee3
        ntoskrnl.exe @ 0x82610000
                Trap added @ PA 0x26eeee3 RPA 0xff005ee3 Page 9966 for KeBugCheck. 
```

From _WinDbg_:
```
nt!KeBugCheck:
826eeee3 8bff mov edi,edi
...
nt!KeBugCheckEx:
826eef02 8bff mov edi,edi
```

**Comment by tklengyel** [comment]
@skvl So WinDbg should not see the hooks (that's the whole point of DRAKVUF) ;) It does look like DRAKVUF trapped the correct addresses though:
> [BSODMON] [KeBugCheck] RVA 0xdeee3
        ntoskrnl.exe @ 0x82610000
                Trap added @ PA 0x26eeee3 RPA 0xff005ee3 Page 9966 for KeBugCheck. 

`0x82610000 +  0xdeee3 = 0x826eeee3`.

So the hook should be triggered when it gets called. It does look like both hooks you install are on the same page. Can you try adding just the hook for `KeBugCheck` and see if that makes a difference?

**Comment by skvl** [comment]
Yes. You are right. I have hooked `KeBugCheck2()` only on _x86_ and this works! But now I have some problems with _x64_. It freezes!

**Comment by tklengyel** [comment]
I don't know why that would be, your changes should make no difference for `x64`.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by skvl** [comment]
@tklengyel this is not a freeze! This is just a Windows kernel with debug switched on! So it sits there and waits for _WinDbg_.

**Comment by tklengyel** [comment]
@skvl this looks good to me as is, does `KeBugCheck2` trigger on x86 as expected?

**Comment by skvl** [comment]
@tklengyel I think yes:
```
nt!KeBugCheck:
826eeee3 8bff            mov     edi,edi
826eeee5 55              push    ebp
826eeee6 8bec            mov     ebp,esp
826eeee8 33c0            xor     eax,eax
826eeeea 50              push    eax
826eeeeb 50              push    eax
826eeeec 50              push    eax
826eeeed 50              push    eax
826eeeee 50              push    eax
826eeeef ff7508          push    dword ptr [ebp+8]
826eeef2 e8f0050000      call    nt!KeBugCheck2 (826ef4e7)
...
nt!KeBugCheckEx:
826eef02 8bff            mov     edi,edi
826eef04 55              push    ebp
826eef05 8bec            mov     ebp,esp
826eef07 83e4f8          and     esp,0FFFFFFF8h
826eef0a 6a00            push    0
826eef0c ff7518          push    dword ptr [ebp+18h]
826eef0f ff7514          push    dword ptr [ebp+14h]
826eef12 ff7510          push    dword ptr [ebp+10h]
826eef15 ff750c          push    dword ptr [ebp+0Ch]
826eef18 ff7508          push    dword ptr [ebp+8]
826eef1b e8c7050000 call nt!KeBugCheck2 (826ef4e7)
```

**Comment by aoshiken** [comment]
My apologies for being late...

@skvl: as you can see below on Windows 7 SP1 x64 platform `KeBugCheck` calls `KeBugCheckEx` which  ends up with two branches both calling `KeBugCheck2` so I'm confident you can use the same hook for both platforms:

```
kd> u nt!KeBugCheck
nt!KeBugCheck:
fffff800`0289a610 4883ec28           sub     rsp,28h
fffff800`0289a614 e827000000         call    nt!KeBugCheckEx (fffff800`0289a640)

kd> u nt!KeBugCheckEx+0xf5 nt!KeBugCheckEx+0x11c
nt!KeBugCheckEx+0xf5:
fffff800`0289a735 4c8b442450         mov     r8,qword ptr [rsp+50h]
fffff800`0289a73a 488b542448         mov     rdx,qword ptr [rsp+48h]
fffff800`0289a73f e81c7d0e00         call    nt!KeBugCheck2 (fffff800`02982460)
fffff800`0289a744 90                 nop
fffff800`0289a745 48c744242000000000 mov   qword ptr [rsp+20h],0
fffff800`0289a74e 4533c9             xor     r9d,r9d
fffff800`0289a751 4533c0             xor     r8d,r8d
fffff800`0289a754 33d2               xor     edx,edx
fffff800`0289a756 e8057d0e00         call    nt!KeBugCheck2 (fffff800`02982460)
fffff800`0289a75b 90                 nop
```

**Comment by aoshiken** [comment]
@tklengyel: ASAP

**Comment by skvl** [comment]
@aoshiken thank You very much!

**Pull request merged**
