### PR TITLE
use vmi_pause_vm/vmi_resume_vm instead of xen_pause/xen_resume

### PR DESCRIPTION
**Pull request by disaykin**

### CODE REVIEW

**Comment by tklengyel** [comment]
Might as well remove xen_pause/xen_resume completely as part of this PR.

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by disaykin** [comment]
I also remove xen_pause/xen_resume from libxen_helper

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by disaykin** [comment]
@tklengyel After run with sanitizers, I realize that I was wrong. I rework MR using explicit calls to xen_pause/xen_resume when libvmi does not initialized yet or already destroyed.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by disaykin** [comment]
@tklengyel I can't reproduce the error.
```
DRAKVUF origin/src/injector v1.1-git20230310023344+ptms.sandbox.drakvuf-4.8.0.157-120-g7158e489-1 Copyright (C) 2014-2023 Tamas K Lengyel
Injector starting calc.exe through PID 3744 TID: 0
[INJECT] TIME:1678867691.040104 METHOD:CreateProc STATUS:SUCCESS PID:3744 FILE:"calc.exe" ARGUMENTS:"" INJECTED_PID:1492 INJECTED_TID:4972
Process startup success
DRAKVUF origin/src/injector v1.1-git20230310023344+ptms.sandbox.drakvuf-4.8.0.157-120-g7158e489-1 Copyright (C) 2014-2023 Tamas K Lengyel
Injector starting calc.exe through PID 3744 TID: 0
[INJECT] TIME:1678867691.501047 METHOD:ShellExec STATUS:SUCCESS PID:3744 FILE:"calc.exe" ARGUMENTS:"" INJECTED_PID:0 INJECTED_TID:0
Process startup success
```

Can you help me with ideas?

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
Seems like the error gone away after a reboot of the CI

**Pull request merged**
