### PR TITLE
injector: fix bugs in writefile method

### PR DESCRIPTION
**Pull request by icedevml**
fix some bugs in writefile method in injector, gracefully handle the situation when there was an error opening/writing/closing file

### CODE REVIEW

**Comment by icedevml** [comment]
@tklengyel I've spotted that if `-I <thread_id>` is not provided by the user, injector would use arbitrary thread within the process and if the injection chain is long, different parts of the chain might be executed within different threads because `target_tid = 0` so the TID check is skipped by the `int3_cb` in injector.

The thread ID gets pinned in `injector_set_hijacked`, but this function is called very lately in some methods.

Is it a bug or feature? I think if the thread ID is not provided, we should take a random TID and immediately pin to it to make sure that whole injection chain is executed from this thread. I saw there is some unstability introduced by not doing this.

**Comment by icedevml** [comment]
I took c0bcb599ca7b554b38f4bed40eb33369e0c65ca8 and added the following extra printout:
```cpp
diff --git a/src/libinjector/win_injector.c b/src/libinjector/win_injector.c
index f37d634..4262065 100644
--- a/src/libinjector/win_injector.c
+++ b/src/libinjector/win_injector.c
@@ -936,7 +936,7 @@ static event_response_t injector_int3_cb(drakvuf_t drakvuf, drakvuf_trap_info_t*
 {
     injector_t injector = info->trap->data;

-    PRINT_DEBUG("INT3 Callback @ 0x%lx. CR3 0x%lx. vcpu %i\n", info->regs->rip, info->regs->cr3, info->vcpu);
+    PRINT_DEBUG("INT3 Callback @ 0x%lx. CR3 0x%lx. vcpu %i, TID %u\n", info->regs->rip, info->regs->cr3, info->vcpu, info->proc_data.tid);

     if ( info->proc_data.pid != injector->target_pid )
     {
```

Launched injector this way:
```
injector -v -r /var/lib/drakrun/profiles/kernel.json -d vm-1 -i 1896 -e "%USERPROFILE%\\Desktop\\lol$RANDOM.exe" -B /root/sample.exe -m writefile
```

And look at the logs:
```
Starting injection loop
1597247174.673456 Started DRAKVUF loop
1597247174.674657 CR3 cb on vCPU 0: 0x5ba45000
CR3 changed to 0x5ba45000. PID: 356 PPID: 340 TID: 420
1597247174.674981 CR3 cb on vCPU 0: 0x187000
CR3 changed to 0x187000. PID: 0 PPID: 0 TID: 0
1597247174.690269 CR3 cb on vCPU 0: 0x5ba45000
CR3 changed to 0x5ba45000. PID: 356 PPID: 340 TID: 420
1597247174.690462 CR3 cb on vCPU 0: 0x187000
CR3 changed to 0x187000. PID: 0 PPID: 0 TID: 0
1597247174.690517 CR3 cb on vCPU 1: 0xbc8a000
CR3 changed to 0xbc8a000. PID: 1896 PPID: 432 TID: 1892
1597247174.690707 Breakpoint VA 0x776e933a -> PA 0x62d6433a
1597247174.690726 Physmap populated? 0
1597247174.690778 Copied trapped page to new location
1597247174.690785 Activating remapped gfns in the altp2m views!
1597247174.690821               Trap added @ PA 0x62d6433a RPA 0xff00133a Page 404836 for entry.
Got return address 0x776e933a from trapframe and it's now trapped!
INT3 Callback @ 0x776e933a. CR3 0xbc8a000. vcpu 1, TID 1892
1597247174.691185 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x776e933a. CR3 0xbc8a000. vcpu 1, TID 1892
Writing to allocated virtual memory to allocate physical memory..
Payload is at: 0x97d0000
1597247174.691563 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x776e933a. CR3 0xbc8a000. vcpu 1, TID 1892
Expanding shell...
1597247174.692927 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x776e933a. CR3 0xbc8a000. vcpu 1, TID 1892
Env expand status: 25
Expanded: C:\Users\janusz\Desktop\lol26489.exe
Opening file...
1597247174.693289 Switching altp2m and to singlestep on vcpu 1
1597247174.695186 CR3 cb on vCPU 1: 0x187000
1597247174.705894 CR3 cb on vCPU 0: 0x5ba45000
1597247174.706092 CR3 cb on vCPU 0: 0x187000
1597247174.706131 CR3 cb on vCPU 1: 0xbc8a000
1597247174.707021 CR3 cb on vCPU 1: 0x187000
1597247174.707064 CR3 cb on vCPU 0: 0xbc8a000
INT3 Callback @ 0x776e933a. CR3 0xbc8a000. vcpu 0, TID 2952
File create result 1
Writing file...
Amount: ffff8
Writing...
1597247174.720119 Switching altp2m and to singlestep on vcpu 0
1597247174.720915 CR3 cb on vCPU 1: 0xbc8a000
INT3 Callback @ 0x776e933a. CR3 0xbc8a000. vcpu 0, TID 2952
Writing file...
Amount: 1fd98
Writing...
1597247174.724111 Switching altp2m and to singlestep on vcpu 0
INT3 Callback @ 0x776e933a. CR3 0xbc8a000. vcpu 0, TID 2952
Writing file...
Amount: 0
Finishing
1597247174.724926 Switching altp2m and to singlestep on vcpu 0
INT3 Callback @ 0x776e933a. CR3 0xbc8a000. vcpu 0, TID 2952
Close handle RAX: 0x0
Failed to close guest file handle
1597247174.725174 Switching altp2m and to singlestep on vcpu 0
1597247174.725871 CR3 cb on vCPU 0: 0x16756000
```

```
$ cat logs | grep TID
CR3 changed to 0x5ba45000. PID: 356 PPID: 340 TID: 420
CR3 changed to 0x187000. PID: 0 PPID: 0 TID: 0
CR3 changed to 0x5ba45000. PID: 356 PPID: 340 TID: 420
CR3 changed to 0x187000. PID: 0 PPID: 0 TID: 0
CR3 changed to 0xbc8a000. PID: 1896 PPID: 432 TID: 1892
INT3 Callback @ 0x776e933a. CR3 0xbc8a000. vcpu 1, TID 1892
INT3 Callback @ 0x776e933a. CR3 0xbc8a000. vcpu 1, TID 1892
INT3 Callback @ 0x776e933a. CR3 0xbc8a000. vcpu 1, TID 1892
INT3 Callback @ 0x776e933a. CR3 0xbc8a000. vcpu 1, TID 1892 <--- RACE?
INT3 Callback @ 0x776e933a. CR3 0xbc8a000. vcpu 0, TID 2952 <--- RACE?
INT3 Callback @ 0x776e933a. CR3 0xbc8a000. vcpu 0, TID 2952
INT3 Callback @ 0x776e933a. CR3 0xbc8a000. vcpu 0, TID 2952
INT3 Callback @ 0x776e933a. CR3 0xbc8a000. vcpu 0, TID 2952
```

So half of the injection chain was executed from TID 1892 and half from TID 2952. Moreover, I think these two callbacks marked with `RACE?` were executed in the same time and the whole injection broke because the next step was executed before the previous one was actually completed.

**Comment by icedevml** [comment]
I will fix this by checking if `injector->target_tid == 0` in `int3_cb` and if so, it will be set to the current TID so the whole injection chain will execute within single thread.

**Comment by tklengyel** [comment]
> we should take a random TID and immediately pin to it to make sure that whole injection chain is executed from this thread

That's how it should be, if it's not, that's a bug

**Pull request merged**
