### PR TITLE
fix: add target_rsp checks into filedelete plugin

### PR DESCRIPTION
**Pull request by disaykin**
* add target_rsp checks on exit from injected calls
 * replace manual lock management by RAII
 * restore RIP and PSP registers after injection

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by disaykin** [comment]
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
