### PR TITLE
LIBINJECTOR: Filter exits from injected calls by target rsp

### PR DESCRIPTION
**Pull request by disaykin**

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@disaykin some injection are now hanging for 5+ minutes before getting killed by the timeout although the injection itself was succesful

**Comment by disaykin** [comment]
@tklengyel thanks. I try catch and debug this behaivour.

**Comment by tklengyel** [comment]
@disaykin AFAICT the injections that are hanging are the ones initiated through the `drakvuf` binary, not through `injector`.

**Comment by disaykin** [comment]
@tklengyel I can't reproduce the hang behaviour. Can you give me debug logs for the hung case, please?

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
