### PR TITLE
filetracer refactoring

### PR DESCRIPTION
**Pull request by EscardosS**
Hello, I refactored windows part of filetracer

### CODE REVIEW

**Comment by EscardosS** [comment]
Also i want to change this part and retreive enums from ole32:

```
// TODO Remove hard-code. Retrieve from Volatility3 profile: profile["enums"]["_FILE_INFORMATION_CLASS"]
#define FILE_BASIC_INFORMATION 4
#define FILE_RENAME_INFORMATION 10
#define FILE_DISPOSITION_INFORMATION 13
#define FILE_END_OF_FILE_INFORMATION 20

```
But I didn't find a suitable function

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by EscardosS** [comment]
CI error, which is not related to the plugin (plugin won't start without ole32.json -> plugin can't cause this error)

https://ci.drakvuf.com/job/DRAKVUF-windows7-sp1-x64/1206/console
`VMI_ERROR: xen_request_page_fault error -1 injecting page fault exception`

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
