### PR TITLE
Fix libusermode trap removing on process termination

### PR DESCRIPTION
**Pull request by disaykin**
Fixed a bug with removing usermode hooks from a process, which calls a termination of another process.

### CODE REVIEW

**Comment by disaykin** [comment]
@BonusPlay @icedevml Please review the code

**Comment by BonusPlay** [comment]
This shares plenty of changes with #1226, could you either split them entierly or merge them together?

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by disaykin** [comment]
@BonusPlay I rebase MR #1226 on top of master after merging this PR.

**Comment by BonusPlay** [comment]
The code looks good, question is why doing it by PID is better than by CR3? Does it fix some multi-threaded black magic?

**Comment by disaykin** [comment]
The only reason for this change that I need the PID to glue the installed hooks with the NtTerminateProcess argument.

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Review by BonusPlay — APPROVED** [review]

**Pull request merged**
