### PR TITLE
libusermode: print argument names

### PR DESCRIPTION
**Pull request by skvl**

### CODE REVIEW

**Comment by BonusPlay** [comment]
What happened that `using ArgumentPrinter::ArgumentPrinter;` needed to be added everywhere?

**Comment by skvl** [comment]
@BonusPlay, I've been motivated by https://en.cppreference.com/w/cpp/language/using_declaration , _Inheriting constructors_.

So since `StringPrinterInterface` constructor should be a copy of `ArgumentPrinter` constructor, I have inherited the constructor so not have to write it again.

Am I wrong?

**Comment by BonusPlay** [comment]
Oh, now I see. :+1:

**Comment by skvl** [comment]
@tklengyel is this ok? I can't access jenkins page.

**Comment by icedevml** [comment]
@drakvuf-jenkins This is OK to test.

**Comment by icedevml** [comment]
The CI box seems to be currently down

**Comment by skvl** [comment]
@drakvuf-jenkins retest this please.

**Comment by skvl** [comment]
@tklengyel what is the error with [Windows 10](https://ci.drakvuf.com/job/DRAKVUF-windows10-2004/215/)?

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
