### PR TITLE
libdrakvuf: fix memory leak on WoW offsets

### PR DESCRIPTION
**Pull request by skvl**
Relates to #1174

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by skvl** [comment]
@tklengyel is there some error on CI? As far as I understand it fails to create a VM.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@skvl Yea, the win10 vm failed to restore from the savefile for some reason. I just resaved it and now its back to normal `¯\_(ツ)_/¯`

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
