### PR TITLE
libusermode: fix CLSID printing

### PR DESCRIPTION
**Pull request by skvl**

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by skvl** [comment]
! will re-base this in a minute.

**Comment by skvl** [comment]
@tklengyel could re-run Jenkins please?

**Comment by icedevml** [comment]
@drakvuf-jenkins Retest this please.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by icedevml** [comment]
huh, race condition :D

**Comment by tklengyel** [comment]
> huh, race condition :D

It will be very well tested at least :)

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
