### PR TITLE
libusermode: extract common logic in PF and injection mode

### PR DESCRIPTION
**Pull request by disaykin**

### CODE REVIEW

**Comment by disaykin** [comment]
```
src/xen_helper/meson.build:9:0: ERROR: Include dir /usr/local/include does not exist.

A full log can be found at /home/runner/work/drakvuf/drakvuf/build/meson-logs/meson-log.txt
Error: Process completed with exit code 1.
```

**Comment by tklengyel** [comment]
> ```
> src/xen_helper/meson.build:9:0: ERROR: Include dir /usr/local/include does not exist.
> 
> A full log can be found at /home/runner/work/drakvuf/drakvuf/build/meson-logs/meson-log.txt
> Error: Process completed with exit code 1.
> ```

Yea, not sure what's up with the infer ci check but we can just ignore it for now. I might just disable that checker altogether.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by disaykin** [comment]
@tklengyel I fix memory leak in #1747

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by tklengyel** [comment]
Could you rebase this on the latest master?

**Comment by disaykin** [comment]
@tklengyel Done

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Pull request merged**
