### PR TITLE
Partially revert PR #1661

### LINKED ISSUE #1673: Error with filetracer & ole32 pdb
after @EscardosS refactor on filetracer, plugin doesnt work.
commit says we need to use ole32.json to use plugin but i cant convert ole32.pdb to json format with volatility and drakpdb

can you show me a way

### PR DESCRIPTION
**Pull request by tklengyel**
Fixes #1673

### CODE REVIEW

**Comment by EscardosS** [comment]
Actually almost every offset from ole32, exept `_FILE_ALL_INFORMATION_BasicInformation`, can be extracted from `kernel.json` too.

So only this is truly needed:
```
        case FileAllInformation:
            if ( this->ole32_profile )
```

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
