### PR TITLE
Make universal functions to setup stack accessable globally

### PR DESCRIPTION
**Pull request by skvl**
This allows to call those functions from other places such as plugins.

More over fix stack alignment bug.

### CODE REVIEW

**Comment by skvl** [comment]
@tklengyel I'm very sorry but I don't understand the error from Travis-CI. I could build this successfully.

**Comment by tklengyel** [comment]
It's unrelated to this PR, just rebase on the latest master and it will go away.

**Comment by skvl** [comment]
@tklengyel could you pleas merge this branch if everything is OK.

**Comment by tklengyel** [comment]
Will do, want to push it through Jenkins first.

**Pull request merged**
