### PR TITLE
[Linux] add writefile method to injector

### PR DESCRIPTION
**Pull request by manorit2001**
This PR adds `writefile` method to linux injector

Depends on https://github.com/tklengyel/drakvuf/pull/1283

### CODE REVIEW

**Comment by tklengyel** [comment]
Please rebase on master

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
Please rebase on master

**Comment by manorit2001** [comment]
> Please rebase on master

done

**Pull request merged**
