### PR TITLE
rebootmon: new plugin for monitoring of system reboot events

### PR DESCRIPTION
**Pull request by disaykin**
This plugin allows detect such system reboot events as halt, reboot, power off and can break drakvuf event loop before VM destruction caused by such events.

Use drakvuf command line option "--rebootmon-abort-on-power-off" for enabling loop break mode.

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by disaykin** [comment]
Fails on win7. But rebootmon plugin works only on Linux VMs.
I think this is false positive.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
