### PR TITLE
Rootkitmon callbackmon callbacks

### PR DESCRIPTION
**Pull request by archercreat**
Hello. In this pr I moved object enumeration apis to global drakvuf namespace, moved callback checks from rootkitmon to callbackmon and added missing win offset.

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by archercreat** [comment]
@tklengyel there's something wrong with ci I think, this lines does not look right:
```
DRAKVUF is running with PID 688443, background pid is 688440
```

**Comment by tklengyel** [comment]
That line is fine, what seems to be more of an issue is: `timeout: the monitored command dumped core`

**Comment by archercreat** [comment]
Could you restart ci please?

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by archercreat** [comment]
Hello, is there any way to retrieve core dump from ci pipeline?

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
Unfortunately the crashdump doesn't have any backtrace and I can't reproduce the crash through gdb

**Comment by archercreat** [comment]
I'll try to split into multiple pull requests

**Pull request closed without merging**
