### PR TITLE
Fix Coverity

### PR DESCRIPTION
**Pull request by icedevml**

### CODE REVIEW

**Comment by icedevml** [comment]
I've tried to fix something here https://github.com/icedevml/drakvuf-coverity-test

but I can't get past >78% succesfully compiled units and during some units `cov-internal-emit-clang`  gets SIGSEGV. Giving up for now :(

**Comment by tklengyel** [comment]
Yeap, thats where I got stuck too. No clue what coverity is doing..

**Comment by icedevml** [comment]
This error pattern (SIGSEGV with backtrace leading to libc) also happens in some other projects that are using clang, I think this should be reported upstream to Coverity

**Comment by icedevml** [comment]
I will send a bug report to Coverity

**Pull request closed without merging**
