### PR TITLE
libusermode,apimon,memdump: print CLSID from dll hook list

### PR DESCRIPTION
**Pull request by skvl**
This allows to provide a CLSID in dll hooks list which is used as meta information to link multiple events in output e.g.:
```
System32\taskschd.dll,ITaskService::GetFolder,clsid,0F87369F-A4E5-4CFC-BD3E-73E6154572DD,20520,log,this:lpvoid,path:bstr,ppFolder:lpvoid*
```

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by skvl** [comment]
@tklengyel is [this](https://ci.drakvuf.com/job/DRAKVUF-windows7-sp1-x86/114/console) the resource error once again?

**Comment by tklengyel** [comment]
@skvl this looks like something else, Valgrind seems to have failed to start on the Win7 x86 VM. Don't know why.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by skvl** [comment]
@tklengyel this looks like OK now.

**Comment by skvl** [comment]
@tklengyel, @icedevml, is this PR OK?

**Comment by tklengyel** [comment]
@sklv LGTM but I would like another set of eyes on the `libusermode` changes

**Comment by icedevml** [comment]
I will look soon

**Review by icedevml — APPROVED** [review]
this PR includes some refactor to the libusermode API, as far as I've studied it, looks OK

thanks for putting effort in improving code quality in libusermode

**Pull request merged**
