### PR TITLE
Fix some possible deadlocks

### PR DESCRIPTION
**Pull request by skvl**
@tklengyel, I just have found some issue while using `vmi_lock_guard` in plugin initialization.

In _socketmon_ I caught a deadlock in enumerating processes after initializing a `vmi_lock_guard`.

I fixed similar place in _userhook_ too just for sure.

### CODE REVIEW

**Comment by tklengyel** [comment]
Huh, you can't use `vmi_lock_guard` in the function's context? It has to be restricted to another `{}` scope within?

**Comment by skvl** [comment]
Yes. Prior that was in function context. In result I found that back-trace in GDB:
```
#2  0x0000000000415d12 in drakvuf_lock_and_get_vmi (drakvuf=0x2044880) at drakvuf.c:442
#3  0x000000000048702d in module_trap_visitor (drakvuf=0x2044880, module_info=0x5b80000, visitor_ctx=0x7ffeaaa77f88) at socketmon/socketmon.cpp:796                                          
#4  0x000000000042127e in win_search_modules (drakvuf=drakvuf@entry=0x2044880, module_name=module_name@entry=0x5698e5 "dnsapi.dll",                                                          
    visitor_func=visitor_func@entry=0x486ea0 <module_trap_visitor(drakvuf*, _module_info const*, void*)>, visitor_ctx=visitor_ctx@entry=0x7ffeaaa77f88,                                      
    eprocess_addr=eprocess_addr@entry=18446691329884643904, wow_process=wow_process@entry=0, pid=604, ctx=0x7ffeaaa77ed0) at win-processes.c:730                                             
#5  0x0000000000421d28 in win_enumerate_processes_with_module (drakvuf=0x2044880, module_name=0x5698e5 "dnsapi.dll",                                                                         
    visitor_func=0x486ea0 <module_trap_visitor(drakvuf*, _module_info const*, void*)>, visitor_ctx=0x7ffeaaa77f88) at win-processes.c:984                                                    
#6  0x0000000000486dc1 in register_module_trap (drakvuf=0x2044880, trap=0x5bb7c20, module_name=0x5698e5 "dnsapi.dll", function_name=0x569963 "DnsQuery_W",                                   
    hook_cb=0x484b00 <trap_DnsQuery_W_cb(drakvuf*, drakvuf_trap_info*)>) at socketmon/socketmon.cpp:830                                                                                      
#7  0x0000000000484af9 in register_dnsapi_trap (drakvuf=0x2044880, trap=0x5bb7c20, function_name=0x569963 "DnsQuery_W", hook_cb=0x484b00 <trap_DnsQuery_W_cb(drakvuf*, drakvuf_trap_info*)>) 
    at socketmon/socketmon.cpp:841
#8  0x00000000004846af in socketmon::socketmon (this=0x5bb7bc0, drakvuf=0x2044880, c=0x7ffeaaa78420, output=OUTPUT_KV) at socketmon/socketmon.cpp:870                                        
#9  0x0000000000425940 in drakvuf_plugins::start (this=0x2dd3800, plugin_id=PLUGIN_SOCKETMON, options=0x7ffeaaa789a0) at plugins.cpp:230                                                     
#10 0x0000000000414c10 in drakvuf_c::start_plugins (this=0x2042720, plugin_list=0x7ffeaaa78a50, options=0x7ffeaaa789a0) at drakvuf.cpp:155                                                   
#11 0x00000000004147f8 in main (argc=68, argv=0x7ffeaaa78c88) at main.cpp:565
```

**Comment by skvl** [comment]
If we restrict `vmi_lock_guard` in `{}` then it would be released before next line.

**Comment by tklengyel** [comment]
Good to know. Could you check if we perhaps have other unsafe uses of it elsewhere? Would be nice to fix all of them in one go.

**Comment by skvl** [comment]
Sure. All other places looks reasonably good.

I noticed that the same trick have been used in `delaymon::trap_NtDelayExecution_cb`, `socketmon::trap_DnsQueryEx_cb`, `socketmon::trap_DnsQuery_W_cb`, `wmimon::CoCreateInstanse_handler` and `wmimon::wmimon`.

In `envmon::trap_DefineDosDeviceW_cb` and `wmimon::ExecMethod_return_handler` there is other way to achieve the same. Explicitly call `unlock`.

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
Sure but if you have to call unlock you might as well just use the standard libdrakvuf functions to get & release it :)

**Comment by skvl** [comment]
> Sure but if you have to call unlock you might as well just use the standard libdrakvuf functions to get & release it :)

I understand :) I just mentioned other places.

**Pull request merged**
