### PR TITLE
syscalls: fix NtAllocateVirtualMemory prototype

### PR DESCRIPTION
**Pull request by skvl**

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by skvl** [comment]
@tklengyel what's the error with Windows 7 x86? Some problem with CI?

**Comment by icedevml** [comment]
@drakvuf-jenkins Retest this please.

**Comment by icedevml** [comment]
> what's the error with Windows 7 x86? Some problem with CI?

this looks like some random issue

**Review by icedevml — APPROVED** [review]

**Comment by icedevml** [comment]
@skvl please resolve conflict with `syscalls.cpp`

**Comment by skvl** [comment]
@icedevml, done!

**Comment by icedevml** [comment]
@drakvuf-jenkins Retest this please.

**Review by icedevml — APPROVED** [review]

**Pull request merged**
