### PR TITLE
Minor fixes in injector

### PR DESCRIPTION
**Pull request by tklengyel**

### CODE REVIEW

**Comment by disaykin** [comment]
wait_for_process = optarg; => wait_for_process = 1;

**Comment by tklengyel** [comment]
@disaykin please open an issue for the other problem you noted when there are processes with the same name/ppid running already, just so we can keep track of it and it's possible solutions

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by disaykin** [comment]
#474

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
