### PR TITLE
New plugin: memaccessmon

### PR DESCRIPTION
**Pull request by Akenth0r**
Hello! I made this plugin to get more details about memory read\write calls in windows. It shows some useful info about memory call, it's target and also traverses mmvad of target process. For example, it can be useful for credential dumping detection.

### CODE REVIEW

**Review by BonusPlay — COMMENTED** [review]
+- looks ok. I may write `MmvadHook` and update this plugin later on.

**Comment by tklengyel** [comment]
Please fix the issues spotted by CI and add the plugin to the meson build system too.

**Comment by archercreat** [comment]
@tklengyel Should be good now

**Comment by tklengyel** [comment]
@archercreat You'll need to rebase the PR on the latest master branch

**Comment by archercreat** [comment]
@tklengyel Could you please take a look on why tarbuild fails? I don't quite understand

**Comment by archercreat** [comment]
@tklengyel rebased, should be good

**Comment by archercreat** [comment]
@tklengyel Hello! Sorry for the ping. Is there anything left to do it this pr?

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Test this please

**Comment by tklengyel** [comment]
Looks like there is a memory leak caught with this plugin enabled. Are you sure you don't have to free your unordered_map when the plugin is exiting?

**Comment by archercreat** [comment]
Indeed, the process name field is not freed at the end. Thanks for noticing.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
