### PR TITLE
Add new hooks

### PR DESCRIPTION
**Pull request by skvl**
* plugins/procmon: add hook for NtAdjustPrivilegesToken
* plugins/filetracer: hook return from NtCreateFile to get file handle

### CODE REVIEW

**Comment by skvl** [comment]
@tklengyel I will rebase the branch after you accept previous one.

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by skvl** [comment]
@tklengyel what is the error?

**Comment by tklengyel** [comment]
Both the 32-bit and the 64-bit Win7 VMs crash.

**Comment by skvl** [comment]
I will try to debug it. So leave the branch to the end.

**Comment by skvl** [comment]
@tklengyel I have fixed the bug.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
