### PR TITLE
Pass the control to the original exception handler in case of DLL is …

### PR DESCRIPTION
**Pull request by disaykin**
…already hooked

@kscieslinski @BonusPlay @chivay

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
LGTM, will wait for people cc-d to chime in a bit before merging

**Comment by BonusPlay** [comment]
Wouldn't this cause more, unnecessary BSODs when hooking APIs on CoW pages? 2 processes can use same page with DLL, which can cause 2nd attempt to hook it.

**Comment by disaykin** [comment]
Good question. Maybe it shouldn't use my change.

**Comment by disaykin** [comment]
@BonusPlay Do you have good collection of real samples for checking. On my samples I do not have any BSOD occured.

**Comment by BonusPlay** [comment]
Yes, we even have infrastructure to perform tests like this, but sadly it's not ready yet, so I'll have to do that manually - which will take some time, so the results would probably be next week.

**Comment by tklengyel** [comment]
@BonusPlay were you able to test this PR?

**Comment by disaykin** [comment]
@BonusPlay I read the code. CoW handler do not cause a call of `vmi_request_page_fault` function at all.

**Pull request merged**
