### PR TITLE
enforce usage of vmi_lock_guard RAII pattern. Part 2

### PR DESCRIPTION
**Pull request by disaykin**

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
Is this PR a superset of #1505? Why the separate PR?

**Comment by disaykin** [comment]
At the time of creating of this request, I thought that you would accept that request faster, since it had already passed all the checks.

**Comment by tklengyel** [comment]
OK, you could have just pushed to the branch in that PR but no worries. I'll just merge this and close the other PR.

**Pull request merged**
