### PR TITLE
Save process dumps in minidump (MDMP) format

### PR DESCRIPTION
**Pull request by skvl**
Minidumps is used to analyze with tools like WinDbg, IDA, etc.

The branch is dependent on https://github.com/libvmi/libvmi/pull/892

This is an minimal valuable implementation:
* basic system information: Windows build number, major and minor version, CPUID info, timestamp.
* minimal thread information: segments, general purpose registers
* memory list: list of memory ranges gathered from VAD

This branch just adds meta information to previous process dumps at the beginning of the file.

### CODE REVIEW

**Comment by skvl** [comment]
@tklengyel this is based on https://github.com/tklengyel/drakvuf/pull/856

**Comment by skvl** [comment]
It is convenient to test with [Google Breakpad](https://github.com/google/breakpad):
```bash
$ ./src/processor/minidump_dump -x /path/to/dump/file
```

**Comment by skvl** [comment]
@tklengyel is it OK to you?

**Comment by tklengyel** [comment]
Well, travis is failing this PR at the moment

**Comment by skvl** [comment]
> Well, travis is failing this PR at the moment

Sorry I didn't notice. I have re-based branch onto `master`.

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
