### PR TITLE
Fix print injection status

### PR DESCRIPTION
**Pull request by skvl**
* Fix possible null pointer dereference
* Add printing of crashed processes while injection

### CODE REVIEW

**Comment by skvl** [comment]
@tklengyel I think that error from Travis is not related to my code: https://travis-ci.org/tklengyel/drakvuf/jobs/493898744#L168

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@skvl please rebase this PR so that it doesn't include unrelated commits

**Comment by tklengyel** [comment]
@skvl I think this will need to be rebased to resolve the conflicts

**Comment by skvl** [comment]
@tklengyel Done!

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@skvl This PR is introducing a regression when injecting into a Windows 7 32-bit system with drakvuf itself (not through the standalone injector)

**Comment by skvl** [comment]
@tklengyel could you provide some details? I have found an error in _WoW64_ support last evening. May be the error was due to this?

**Comment by tklengyel** [comment]
I just see that the test consistently fails with injecting through drakvuf. I don't know which part of the PR is causing it. I suggest setting up a 32bit Win7 locally and testing that way.

**Comment by skvl** [comment]
I will retest it.

**Comment by skvl** [comment]
@tklengyel it works for me:
```
sudo drakvuf -d TRAP -r ${DIR}/rekall-kernel.json -T ${DIR}/rekall-tcpip.json -i 1436 -e 'calc.exe'
...
[INJECT] TIME:1551510255.903344 STATUS:SUCCESS PID:1436 FILE:"calc.exe" ARGUMENTS:"" INJECTED_PID:3468 INJECTED_TID:3472
```
win7-x86

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by skvl** [comment]
@tklengyel I think I have found the real reason of fails.

Both clipboardmon and windowmon hooks _win32k.sys_. But parts of it could not be loaded into virtual memory. So one should make this functions to be loaded before running plugins.

I don't know why this did not rise earlier.

**Comment by tklengyel** [comment]
For 31bit Windows I don't have rekall profile for win32k.sys, so those plugins shouldn't have started to begin with.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
This was the output from a failed run from before. It didn't get a successful injection
```
Running DRAKVUF #1 for 30 seconds. Opts:  -i 2028 -e calc.exe -m createproc
DRAKVUF is running with PID 10727
CPU utilization average: 1
Syscalls: 0
1551538407.559174 DRAKVUF v0.6-f9d4690
1551538407.559246 Starting DRAKVUF initialization
1551538407.598885 drakvuf_init: Rekall WoW64 profile not used
1551538407.599149 drakvuf_event_fd_add fd=18
1551538407.599163 size of list=1
1551538407.599168 regenerating event_fds and fd_info_lookup...
1551538407.599173 new event_fd i=0 for fd=18
1551538407.599178 new fd_info_lookup i=0 for fd=18
1551538407.599183 drakvuf_init: adding event_fd done
1551538407.599297 init_vmi on domID 97 -> windows7-sp1-x86-jenkins
1551538407.599863 init_vmi: initializing vmi done
1551538407.599923 init_vmi: initializing vmi paging done
1551538407.633891 init_vmi: initializing vmi OS done
1551538407.633961 Max GPFN: 0xff000
1551538407.633977 Max mem set? 0
1551538407.633995 Physmap populated? 0
1551538407.634032 Altp2m enabled? 0
1551538407.634041 Altp2m view X created? 0 with ID 1
1551538407.634049 Altp2m view R created? 0 with ID 2
1551538407.634067 Switched Altp2m view to X? 0
1551538407.634097 init_vmi finished
1551538407.634112 Windows kernel base address is 0x8261f000
1551538407.634124 Rekall profile: '_EPROCESS' has no 'Wow64Process' member
1551538407.634129 Failed to find offset for _EPROCESS:Wow64Process
1551538407.634134 Rekall profile: '_EPROCESS' has no 'WoW64Process' member
1551538407.634139 Failed to find offset for _EPROCESS:WoW64Process
1551538407.634168 Rekall profile: no '_EWOW64PROCESS' found
1551538407.634173 Failed to find offset for _EWOW64PROCESS:Peb
1551538407.634178 Failed to find offsets for array of structure names and subsymbols.
1551538407.634183 libdrakvuf initialized
1551538407.634189 DRAKVUF initializated
1551538407.634199 Starting injection with PID 2028(0) for calc.exe
Target PID 2028 to start 'calc.exe'
1551538407.634674 Rekall profile: '_KTRAP_FRAME' has no 'Rip' member
1551538407.634682 Failed to find offset for _KTRAP_FRAME:Rip
Failed to find one of offsets.
1551538407.634748 Found PEB @ 0x7ffd7000. LDR @ 0x77837880. INLOADORDER @ 0x4017e0.
1551538407.634788 Found module taskmgr.exe
1551538407.634818 Found module ntdll.dll
1551538407.634827 Found module kernel32.dll
1551538407.634935 	ResumeThread @ 0x75f70f1c
1551538407.634943 Found PEB @ 0x7ffd7000. LDR @ 0x77837880. INLOADORDER @ 0x4017e0.
1551538407.634950 Found module taskmgr.exe
1551538407.634956 Found module ntdll.dll
1551538407.634962 Found module kernel32.dll
1551538407.635009 	CreateProcessW @ 0x75f3204d
Starting injection loop
1551538407.635028 Started DRAKVUF loop
1551538407.635241 CR3 cb on vCPU 1: 0x3e9de0a0
CR3 changed to 0x3e9de0a0. PID: 372 PPID: 364
1551538407.635335 CR3 cb on vCPU 0: 0x3e9de320
CR3 changed to 0x3e9de320. PID: 872 PPID: 312
1551538407.635540 CR3 cb on vCPU 0: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.635672 CR3 cb on vCPU 1: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.635699 CR3 cb on vCPU 0: 0x3e9de320
CR3 changed to 0x3e9de320. PID: 872 PPID: 312
1551538407.635831 CR3 cb on vCPU 0: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.693202 CR3 cb on vCPU 0: 0x3e9de320
CR3 changed to 0x3e9de320. PID: 872 PPID: 312
1551538407.693337 CR3 cb on vCPU 1: 0x3e9de0a0
CR3 changed to 0x3e9de0a0. PID: 372 PPID: 364
1551538407.693687 CR3 cb on vCPU 0: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.693779 CR3 cb on vCPU 1: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.694074 CR3 cb on vCPU 0: 0x3e9de320
CR3 changed to 0x3e9de320. PID: 872 PPID: 312
1551538407.694368 CR3 cb on vCPU 0: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.708957 CR3 cb on vCPU 0: 0x3e9de0a0
CR3 changed to 0x3e9de0a0. PID: 372 PPID: 364
1551538407.709368 CR3 cb on vCPU 0: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.709448 CR3 cb on vCPU 1: 0x3e9de300
CR3 changed to 0x3e9de300. PID: 1840 PPID: 1768
1551538407.711284 CR3 cb on vCPU 1: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.711394 CR3 cb on vCPU 0: 0x3e9de300
CR3 changed to 0x3e9de300. PID: 1840 PPID: 1768
1551538407.715755 CR3 cb on vCPU 1: 0x3e9de300
CR3 changed to 0x3e9de300. PID: 1840 PPID: 1768
1551538407.716315 CR3 cb on vCPU 1: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.717741 CR3 cb on vCPU 0: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.755649 CR3 cb on vCPU 1: 0x3e9de300
CR3 changed to 0x3e9de300. PID: 1840 PPID: 1768
1551538407.755943 CR3 cb on vCPU 0: 0x3e9de320
CR3 changed to 0x3e9de320. PID: 872 PPID: 312
1551538407.756243 CR3 cb on vCPU 0: 0x3e9de0a0
CR3 changed to 0x3e9de0a0. PID: 372 PPID: 364
1551538407.756654 CR3 cb on vCPU 1: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.756774 CR3 cb on vCPU 0: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.802454 CR3 cb on vCPU 1: 0x3e9de1a0
CR3 changed to 0x3e9de1a0. PID: 736 PPID: 424
1551538407.803222 CR3 cb on vCPU 1: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.818089 CR3 cb on vCPU 1: 0x3e9de0a0
CR3 changed to 0x3e9de0a0. PID: 372 PPID: 364
1551538407.818258 CR3 cb on vCPU 0: 0x3e9de320
CR3 changed to 0x3e9de320. PID: 872 PPID: 312
1551538407.818512 CR3 cb on vCPU 0: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.818586 CR3 cb on vCPU 1: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.818829 CR3 cb on vCPU 0: 0x3e9de320
CR3 changed to 0x3e9de320. PID: 872 PPID: 312
1551538407.819092 CR3 cb on vCPU 0: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.880374 CR3 cb on vCPU 0: 0x3e9de320
CR3 changed to 0x3e9de320. PID: 872 PPID: 312
1551538407.880502 CR3 cb on vCPU 1: 0x3e9de0a0
CR3 changed to 0x3e9de0a0. PID: 372 PPID: 364
1551538407.880832 CR3 cb on vCPU 1: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.880914 CR3 cb on vCPU 0: 0x185000
CR3 changed to 0x185000. PID: 0 PPID: 0
1551538407.911726 CR3 cb on vCPU 0: 0x3e9de0a0
CR3 changed to 0x3e9de0a0. PID: 372 PPID: 364
1551538407.912153 CR3 cb on vCPU 0: 0x3e9de300
CR3 changed to 0x3e9de300. PID: 1840 PPID: 1768
1551538407.912248 CR3 cb on vCPU 1: 0x3e9de080
CR3 changed to 0x3e9de080. PID: 2028 PPID: 1840
Thread @ 0x84e73d48. ThreadID: 2032
1551538407.974519 Pre mem cb with vCPU 1 @ 0x26ed50b4 in view 128: --x
1551538407.974576 Switching to altp2m view 0 on vCPU 1
1551538407.974583 CR3 cb on vCPU 0: 0x3e9de0a0
1551538407.974648 Post mem cb @ 0x26ed50b4 vCPU 1 altp2m 128
MemX at 0x82a342d8
1551538407.975072 Breakpoint VA 0x82a342d8 -> PA 0x2a342d8
1551538407.975087 Physmap populated? 0
1551538407.975124 Copied trapped page to new location
1551538407.975130 Activating remapped gfns in the altp2m views!
1551538407.975194 		Trap added @ PA 0x2a342d8 RPA 0xff0022d8 Page 10804 for entry. 
Stack setup finished and return trap added @ 0x82a342d8
1551538407.975211 Removed memtrap for GFN 0x21ecd in altp2m view 1
1551538407.975220 Removed memtrap for GFN 0x21dd1 in altp2m view 1
...
1551538407.988320 Removed memtrap for GFN 0x26d41 in altp2m view 1
1551538407.988360 CR3 cb on vCPU 0: 0x3e9de320
1551538407.988451 CR3 cb on vCPU 0: 0x3e9de300
1551538419.149160 CR3 cb on vCPU 0: 0x185000
1551538467.547643 DRAKVUF loop broke unexpectedly: [Errno: 4] Interrupted system call
1551538467.547861 DRAKVUF loop finished
Finished with injection. Ret: 0.
Process startup failed
1551538467.547982 close_vmi starting
1551538467.548139 Removed memtrap for GFN 0xff001 in altp2m view 1
1551538468.237854 close_vmi finished
inject,1551538467.547909,PrematureBreak

**Comment by skvl** [comment]
@tklengyel, UP

**Comment by tklengyel** [comment]
I'm still not convinced `Disable clipboardmon and windowmon by default` is needed

**Comment by skvl** [comment]
This is for users convenience. Because not everyone needs it but enabling this make user to perform extra-actions. If You don't like this I could remove it.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
Well, it is perplexing but with this PR the 32-bit injection is still definitely broken on my side. I can't pinpoint why that is. It's not related to the plugins being enabled/disabled as at this point plugins haven't run yet, this is the log I get:
```
1553529260.596856 DRAKVUF v0.6-ab1be5e
1553529260.596930 Starting DRAKVUF initialization
1553529260.637029 drakvuf_init: Rekall WoW64 profile not used
1553529260.637277 drakvuf_event_fd_add fd=18
1553529260.637293 size of list=1
1553529260.637298 regenerating event_fds and fd_info_lookup...
1553529260.637303 new event_fd i=0 for fd=18
1553529260.637307 new fd_info_lookup i=0 for fd=18
1553529260.637312 drakvuf_init: adding event_fd done
1553529260.637448 init_vmi on domID 84 -> windows7-sp1-x86-jenkins
1553529260.637982 init_vmi: initializing vmi done
1553529260.638042 init_vmi: initializing vmi paging done
1553529260.672249 init_vmi: initializing vmi OS done
1553529260.672320 Max GPFN: 0xff000
1553529260.672335 Max mem set? 0
1553529260.672354 Physmap populated? 0
1553529260.672393 Altp2m enabled? 0
1553529260.672402 Altp2m view X created? 0 with ID 1
1553529260.672409 Altp2m view R created? 0 with ID 2
1553529260.672427 Switched Altp2m view to X? 0
1553529260.672456 init_vmi finished
1553529260.672471 Windows kernel base address is 0x8261f000
1553529260.672483 Rekall profile: '_EPROCESS' has no 'Wow64Process' member
1553529260.672488 Failed to find offset for _EPROCESS:Wow64Process
1553529260.672493 Rekall profile: '_EPROCESS' has no 'WoW64Process' member
1553529260.672497 Failed to find offset for _EPROCESS:WoW64Process
1553529260.672526 Rekall profile: no '_EWOW64PROCESS' found
1553529260.672531 Failed to find offset for _EWOW64PROCESS:Peb
1553529260.672536 Failed to find offsets for array of structure names and subsymbols.
1553529260.672541 libdrakvuf initialized
1553529260.672546 DRAKVUF initializated
1553529260.672557 Starting injection with PID 2028(0) for calc.exe
Target PID 2028 to start 'calc.exe'
1553529260.673022 Rekall profile: '_KTRAP_FRAME' has no 'Rip' member
1553529260.673029 Failed to find offset for _KTRAP_FRAME:Rip
Failed to find one of offsets.
1553529260.673095 Found PEB @ 0x7ffd7000. LDR @ 0x77837880. INLOADORDER @ 0x4017e0.
1553529260.673135 Found module taskmgr.exe
1553529260.673165 Found module ntdll.dll
1553529260.673173 Found module kernel32.dll
1553529260.673282 	ResumeThread @ 0x75f70f1c
1553529260.673290 Found PEB @ 0x7ffd7000. LDR @ 0x77837880. INLOADORDER @ 0x4017e0.
1553529260.673297 Found module taskmgr.exe
1553529260.673303 Found module ntdll.dll
1553529260.673308 Found module kernel32.dll
1553529260.673356 	CreateProcessW @ 0x75f3204d
Starting injection loop
1553529260.673375 Started DRAKVUF loop
...
CR3 changed to 0x3e9de080. PID: 2028 PPID: 1840
Thread @ 0x84e73d48. ThreadID: 2032
1553529260.904559 Pre mem cb with vCPU 1 @ 0x26ed50b4 in view 128: --x
1553529260.904614 Switching to altp2m view 0 on vCPU 1
1553529260.904620 CR3 cb on vCPU 0: 0x3e9de0a0
1553529260.904697 Post mem cb @ 0x26ed50b4 vCPU 1 altp2m 128
MemX at 0x82a342d8
1553529260.905127 Breakpoint VA 0x82a342d8 -> PA 0x2a342d8
1553529260.905142 Physmap populated? 0
1553529260.905180 Copied trapped page to new location
1553529260.905186 Activating remapped gfns in the altp2m views!
1553529260.905252 		Trap added @ PA 0x2a342d8 RPA 0xff0022d8 Page 10804 for entry. 
Stack setup finished and return trap added @ 0x82a342d8
1553529260.905271 Removed memtrap for GFN 0x140cb in altp2m view 1
...
1553529260.918167 Removed memtrap for GFN 0x26ef5 in altp2m view 1
1553529260.918208 CR3 cb on vCPU 0: 0x3e9de320
1553529260.918333 CR3 cb on vCPU 0: 0x185000
1553529320.588320 DRAKVUF loop broke unexpectedly: [Errno: 4] Interrupted system call
1553529320.588434 DRAKVUF loop finished
Finished with injection. Ret: 0.
Process startup failed
1553529320.588515 close_vmi starting
1553529320.588655 Removed memtrap for GFN 0xff001 in altp2m view 1
1553529321.272118 close_vmi finished
inject,1553529320.588465,PrematureBreak
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by skvl** [comment]
@tklengyel 
> It's not related to the plugins being enabled/disabled as at this point plugins haven't run yet
A have returned the commit with plugins disabled and if I understand right it works now.

The only thing that I don't understand is why this plugins works in _master_ and not works in this branch. If You examine the branch the only thing changed is printing injection status.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
It seems to be passing now but you also have the plugins disabled by default in this PR

**Comment by skvl** [comment]
@tklengyel, it seems to work now.

**Comment by tklengyel** [comment]
@skvl Looks good but I think you included an extra commit that should be a separate PR (filetracer: Print ACLs).

**Comment by skvl** [comment]
This because I have rebased this branch onto that. I will rebase it to master as soon as You will accept those branch.

**Comment by tklengyel** [comment]
@skvl No, please just remove the unnecessary commits from this branch. You can use `git rebase -i HEAD~2` and just remove the last commit

**Comment by skvl** [comment]
@tklengyel, done!

**Pull request merged**
