### PR TITLE
Inject prints program and arguments separately

### PR DESCRIPTION
**Pull request by nystilaps**
Inject prints program and arguments separately

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please.

**Comment by tklengyel** [comment]
Care to provide an example where this would trigger?

**Comment by nystilaps** [comment]
When we run a program with parameters in VM.
For example opening a .PDF / .DOCX document or running a program with several arguments.

**Comment by nystilaps** [comment]
Something like this:
"C:\Program Files (x86)\Microsoft Office\Office12\WINWORD.EXE" "C:\Program Files (x86)\Microsoft Office\Office12\Document.doc" 
FILE:"C:\Program Files (x86)\Microsoft Office\Office12\WINWORD.EXE" 
ARGUMENTS:"\"C:\\Program Files (x86)\\Microsoft Office\\Office12\\Document.doc\""

**Comment by nystilaps** [comment]
How is it going?

**Comment by tklengyel** [comment]
I would like it a lot better if you used g_strsplit (https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-strsplit) instead of a custom implementation.

**Comment by nystilaps** [comment]
Ok, I will try to use it instead.

**Comment by nystilaps** [comment]
Done.

**Comment by nystilaps** [comment]
Done

**Comment by tklengyel** [comment]
Thanks, it looks good now!

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please.

**Pull request merged**
