### PR TITLE
rpcmon: add new plug-in

### PR DESCRIPTION
**Pull request by skvl**
This plug-in allows to trace NdrXxx family of functions from `rpcrt4.dll`.

This on-going work. Though I would like to share is as soon as possible to avoid re-base conflicts in the future.

This branch depends on #999

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by skvl** [comment]
@tklengyel @icedevml I've rebased the branch

**Comment by skvl** [comment]
@tklengyel @icedevml I have re-based the after #999. Let me know if there are some issues with it.

**Comment by skvl** [comment]
@tklengyel @icedevml what's the matter with the PR?

**Review by icedevml — COMMENTED** [review]
I've reviewed this very briefly but it looks OK in terms of usage of `libusermode`.

**Pull request merged**
