### PR TITLE
injector: improve logging and error handling

### PR DESCRIPTION
**Pull request by icedevml**
* make a printout when there is a LibVMI initialization problem (currently there is an exit_code = 1 with empty output);
* report actual error codes to allow distinguish if the file doesn't exist, there is some a permission problem or different cause;
* properly handle problems with file open on the host side;

### CODE REVIEW

**Comment by icedevml** [comment]
@drakvuf-jenkins Retest this please.

**Comment by icedevml** [comment]
@drakvuf-jenkins Retest this please.

**Comment by icedevml** [comment]
@drakvuf-jenkins Retest this please.

**Comment by icedevml** [comment]
@tklengyel could you confirm this CI error is related to the CI itself or actually this PR?

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by icedevml** [comment]
@drakvuf-jenkins Retest this please

**Comment by tklengyel** [comment]
Well, it's sometimes the win7 x86 can't find pid4 error, which has happened before so it's likely unrelated, but sometimes Win10 2004 test fails, which is new. I'll check how it behaves with master.

**Comment by icedevml** [comment]
95% this PR only touches `-m readfile/writefile` so the CI regression went from somewhere else

**Comment by tklengyel** [comment]
I moved Xen to 4.15-rc3 recently and upped the dom0 kernel. May just need to restart and resave the VMs.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
