### PR TITLE
Fix CID 189192

### PR DESCRIPTION
**Pull request by tklengyel**
Potential NULL-pointer dereference on wsc

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please.

**Comment by disaykin** [comment]
@tklengyel Hi, can you tell me, how I can check patches by coverity before PR.

**Comment by tklengyel** [comment]
@disaykin You can register for free at https://scan.coverity.com/ and then you create a `staging` branch in your repo and modify the Travis script to trigger Coverity on that branch. Once you have another branch you want to test, you just merge into your staging branch and push it into your repo and it will run automatically.

**Comment by disaykin** [comment]
@tklengyel Thanks!

**Pull request merged**
