### PR TITLE
procmon: refactor printing privileges with new printing API

### PR DESCRIPTION
**Pull request by skvl**
Split #975

### CODE REVIEW

**Comment by skvl** [comment]
@tklengyel , @icedevml , could you ask @drakvuf-jenkins retest this please

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by skvl** [comment]
@tklengyel https://ci.drakvuf.com not working

**Comment by skvl** [comment]
@tklengyel @icedevml what's the issue?

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
