### PR TITLE
rpcmon: Intercept NdrClientCall3

### PR DESCRIPTION
**Pull request by disaykin**
Intercept NdrClientCall3 and print InterfaceId and TransferSyntax extracted from it arguments.

### CODE REVIEW

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by disaykin** [comment]
Running DRAKVUF #1 for 60 seconds. Opts: -k 0x187000 -i 1568 -e calc.exe -m createproc DRAKVUF startup failed

False positive failure again.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Comment by disaykin** [comment]
I fixed merge conflicts.

**Pull request merged**
