### PR TITLE
memdump: hook MmAccessFault and dump executable regions

### PR DESCRIPTION
**Pull request by skvl**
The new hook dumps those memory regions that not belongs to any loaded module.

This a work in progress. Though I would like to share it to avoid merge conflicts in the future.

### CODE REVIEW

**Comment by icedevml** [comment]
Hi, have you checked Hyperbee plugin? I think it at least partially overlaps with this PR.

**Comment by skvl** [comment]
The performance degradation have been noticed about 15%. Though as I have mentioned this is a work in progress. And this method is optional.

**Comment by skvl** [comment]
@icedevml thanks. I will check it.

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test

**Comment by skvl** [comment]
Close in flavor of #1133

**Pull request closed without merging**
