### PR TITLE
libusermode: add 'lpvoid*' type

### PR DESCRIPTION
**Pull request by skvl**
Re-work #931

### CODE REVIEW

**Comment by icedevml** [comment]
@drakvuf-jenkins This is OK to test.

**Comment by tklengyel** [comment]
@skvl This will need a rebase before I can merge

**Comment by icedevml** [comment]
@skvl do you have `dll-hooks-list` file which actually uses the new features? would be great if you could share it, we do have some examples in the repo (`src/plugins/apimon/example`) so it could be putted there I suppose

**Comment by skvl** [comment]
@tklengyel, done.

**Comment by tklengyel** [comment]
@drakvuf-jenkins Retest this please

**Pull request merged**
