### PR TITLE
Add support for .NET AssemblyNative:::LoadImage hook

### PR DESCRIPTION
**Pull request by BonusPlay**
This also implements userhooks by raw offset instead of only by name.

### CODE REVIEW

**Comment by icedevml** [comment]
@drakvuf-jenkins This is OK to test.

**Comment by tklengyel** [comment]
LGTM

**Comment by tklengyel** [comment]
```
New defect(s) Reported-by: Coverity Scan
Showing 3 of 3 defect(s)


** CID 287087:  Uninitialized members  (UNINIT_CTOR)
/src/libusermode/userhook.hpp: 172 in hook_target_entry_t::hook_target_entry_t(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, unsigned long, unsigned int (*)(drakvuf *, drakvuf_trap_info *), const std::vector<std::unique_ptr<ArgumentPrinter, std::default_delete<ArgumentPrinter>>, std::allocator<std::unique_ptr<ArgumentPrinter, std::default_delete<ArgumentPrinter>>>> &, void *)()


________________________________________________________________________________________________________
*** CID 287087:  Uninitialized members  (UNINIT_CTOR)
/src/libusermode/userhook.hpp: 172 in hook_target_entry_t::hook_target_entry_t(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, unsigned long, unsigned int (*)(drakvuf *, drakvuf_trap_info *), const std::vector<std::unique_ptr<ArgumentPrinter, std::default_delete<ArgumentPrinter>>, std::allocator<std::unique_ptr<ArgumentPrinter, std::default_delete<ArgumentPrinter>>>> &, void *)()
166         hook_target_entry_t(std::string target_name, callback_t callback, const std::vector < std::unique_ptr < ArgumentPrinter > > &argument_printers, void* plugin)
167             : type(HOOK_BY_NAME), target_name(target_name), callback(callback), argument_printers(argument_printers), state(HOOK_FIRST_TRY), plugin(plugin)
168         {}
169     
170         hook_target_entry_t(std::string target_name, addr_t offset, callback_t callback, const std::vector < std::unique_ptr < ArgumentPrinter > > &argument_printers, void* plugin)
171             : type(HOOK_BY_OFFSET), target_name(target_name), offset(offset), callback(callback), argument_printers(argument_printers), state(HOOK_FIRST_TRY), plugin(plugin)
>>>     CID 287087:  Uninitialized members  (UNINIT_CTOR)
>>>     Non-static class member "trap" is not initialized in this constructor nor in any functions that it calls.
172         {}
173     };
174     
175     struct return_hook_target_entry_t
176     {
177         vmi_pid_t pid;

** CID 287086:  Uninitialized members  (UNINIT_CTOR)
/src/libusermode/userhook.hpp: 143 in plugin_target_config_entry_t::plugin_target_config_entry_t(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> &&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> &&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> &&, std::vector<std::unique_ptr<ArgumentPrinter, std::default_delete<ArgumentPrinter>>, std::allocator<std::unique_ptr<ArgumentPrinter, std::default_delete<ArgumentPrinter>>>> &&)()


________________________________________________________________________________________________________
*** CID 287086:  Uninitialized members  (UNINIT_CTOR)
/src/libusermode/userhook.hpp: 143 in plugin_target_config_entry_t::plugin_target_config_entry_t(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> &&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> &&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> &&, std::vector<std::unique_ptr<ArgumentPrinter, std::default_delete<ArgumentPrinter>>, std::allocator<std::unique_ptr<ArgumentPrinter, std::default_delete<ArgumentPrinter>>>> &&)()
137         plugin_target_config_entry_t(std::string&& dll_name, std::string&& function_name, addr_t offset, std::string&& log_strategy, std::vector< std::unique_ptr< ArgumentPrinter > > &&argument_printers)
138             : dll_name(std::move(dll_name)), type(HOOK_BY_OFFSET), function_name(std::move(function_name)), offset(offset), log_strategy(std::move(log_strategy)), argument_printers(std::move(argument_printers))
139         {}
140     
141         plugin_target_config_entry_t(std::string&& dll_name, std::string&& function_name, std::string&& log_strategy, std::vector< std::unique_ptr< ArgumentPrinter > > &&argument_printers)
142             : dll_name(std::move(dll_name)), type(HOOK_BY_NAME), function_name(std::move(function_name)), log_strategy(std::move(log_strategy)), argument_printers(std::move(argument_printers))
>>>     CID 287086:  Uninitialized members  (UNINIT_CTOR)
>>>     Non-static class member "offset" is not initialized in this constructor nor in any functions that it calls.
143         {}
144     };
145     
146     enum target_hook_state
147     {
148         HOOK_FIRST_TRY,

** CID 287085:  Uninitialized members  (UNINIT_CTOR)
/src/libusermode/userhook.hpp: 135 in plugin_target_config_entry_t::plugin_target_config_entry_t()()


________________________________________________________________________________________________________
*** CID 287085:  Uninitialized members  (UNINIT_CTOR)
/src/libusermode/userhook.hpp: 135 in plugin_target_config_entry_t::plugin_target_config_entry_t()()
129         addr_t offset;
130         std::string log_strategy;
131         std::vector< std::unique_ptr< ArgumentPrinter > > argument_printers;
132     
133         plugin_target_config_entry_t()
134             : dll_name(), function_name(), offset(), log_strategy(), argument_printers()
>>>     CID 287085:  Uninitialized members  (UNINIT_CTOR)
>>>     Non-static class member "type" is not initialized in this constructor nor in any functions that it calls.
135         {}
136     
137         plugin_target_config_entry_t(std::string&& dll_name, std::string&& function_name, addr_t offset, std::string&& log_strategy, std::vector< std::unique_ptr< ArgumentPrinter > > &&argument_printers)
138             : dll_name(std::move(dll_name)), type(HOOK_BY_OFFSET), function_name(std::move(function_name)), offset(offset), log_strategy(std::move(log_strategy)), argument_printers(std::move(argument_printers))
139         {}
140

**Comment by BonusPlay** [comment]
Those all known.
> `Non-static class member "trap" is not initialized in this constructor nor in any functions that it calls.`

This part was unmodified by this PR, so I believe it is initialized later (when trap is hit?).

> `Non-static class member "offset" is not initialized in this constructor nor in any functions that it calls.`

This is a ctor for `HOOK_BY_NAME`, which does not initialize offset, because it doesn't know the offset at that time.

> `Non-static class member "type" is not initialized in this constructor nor in any functions that it calls.`

This is basic ctor which expects user to populate it with values manually, so LGTM. Maybe we could add a `INVALID_HOOK_TYPE` as default to prevent some bugs 🤔.

**Comment by tklengyel** [comment]
Yea I think it just means the constructor has to initialize them to some default value (0, NULL etc), even if they are initialized later on by some other function outside the constructor.

**Pull request merged**
